export const APP_VERSION = "PDF_ROUTE_COST_OPTIMIZED_V2";
export const DEFAULT_ITINERARY = "cost_optimized";

const SOURCE_PLAN = "260729_공무 국외출장 계획서(초안)";
const PDF_AIRFARE_BASELINE = 14_495_252;

const e = (
  id,
  day_id,
  time_start,
  time_end,
  title,
  category,
  location,
  transport,
  duration,
  extras = {},
) => ({
  id,
  day_id,
  time_start,
  time_end,
  title,
  category,
  location,
  transport,
  duration,
  original_currency: null,
  original_min: null,
  original_max: null,
  min_cost_krw: null,
  max_cost_krw: null,
  cost_basis: null,
  booking_url: null,
  official_url: null,
  map_url: null,
  notes: null,
  sort_order: (Number(String(id).split("-").pop()) || 0) * 10,
  updated_at: new Date().toISOString(),
  ...extras,
});

const sharedMeta = {
  title: "공무 국외출장 일정·비용 대시보드 2026",
  dates: "2026.09.02–09.12",
  route:
    "인천 → 타이중·루강 → 타오위안 → 암스테르담·로테르담·라이스베이크 → 함부르크 → 에스비에르 → 오르후스 → 코펜하겐 → 인천",
  travelers: 4,
  hotelNights: 8,
  flightNights: 2,
  noHotelStopovers: 2,
  durationText: "9박 11일",
  lodgingNote: "호텔 8박·기내 2박",
  budgetNote:
    "성인 4명·일반석. 항공은 Google Flights 자동조회, 숙박은 예약·검색값(함부르크는 3실 예약), 10% 예비비 포함",
  lastVerified: "2026-08-20-r3",
  sourcePlan: SOURCE_PLAN,
  includesAwtec: false,
  flightCount: 3,
  businessLocationRule: "첨부 계획서 업무장소 + 추가 요청 DNV Hamburg·Skyborn Hamburg·OWC Germany/Denmark 기술미팅",
  pdfAirfareBaseline: PDF_AIRFARE_BASELINE,
};

const planMeta = {
  cost_optimized: {
    ...sharedMeta,
    key: "cost_optimized",
    tabLabel: "추천안 · 비용 최적",
    tabNote: "TPE→AMS 직항 · 귀국 최저가 CPH→CDG→ICN",
    subtitle:
      "첨부 계획서의 도시·업무장소 순서 유지 · 귀국은 9/11 실시간 운임 기준 최저가 1회 경유 · 숙박은 업무 접근성을 지키는 저가 후보",
    taiwanWindow: "9/2 09:40–9/4 11:20",
    taiwanDuration: "약 2일 2시간",
    budgetMin: 17_800_000,
    budgetMax: 23_500_000,
    recommendation:
      "대만·유럽 동선을 단순화하고, 귀국은 CPH→CDG→ICN 1회 경유 최저가를 채택하는 권고안",
  },
  time_optimized: {
    ...sharedMeta,
    key: "time_optimized",
    tabLabel: "비교안 · 귀국시간 우선",
    tabNote: "TPE→AMS 직항 · 귀국 CPH→IST→ICN 08:35 도착",
    subtitle:
      "첨부 계획서의 도시·업무장소 순서 유지 · 귀국은 비용안보다 약 1시간 빠른 이스탄불 1회 환승",
    taiwanWindow: "9/2 09:40–9/4 20:00",
    taiwanDuration: "약 2일 10시간",
    budgetMin: 19_700_000,
    budgetMax: 25_400_000,
    recommendation:
      "TPE→AMS 직항을 유지하고 귀국 도착시각을 우선하는 비교안",
  },
};

function buildDays(mode) {
  const saving = mode === "cost_optimized";
  return [
    {
      id: 1,
      date: "2026-09-02",
      weekday: "수요일",
      cities: "인천 → 타이중항 → 타이중",
      lodging: "CHECK Inn Taichung LaiLai",
      summary:
        "07:55 RMQ 직항 · CHECK Inn LaiLai 짐 보관 · TIPC 회의 · 우치항·가오메이 습지 · 16:00 이후 체크인",
    },
    {
      id: 2,
      date: "2026-09-03",
      weekday: "목요일",
      cities: "타이중 → 루강 → 타이중",
      lodging: "CHECK Inn Taichung LaiLai",
      summary:
        "CHECK Inn LaiLai 숙박 · VESTAS O&M Base 현장·회의 · TIPC 공동 결과공유 · 루강 옛거리",
    },
    {
      id: 3,
      date: "2026-09-04",
      weekday: "금요일",
      cities: "타이중 → 타오위안 → 암스테르담",
      lodging: "기내박",
      summary: "11:00 이전 체크아웃 · 시내 일정 후 호텔 짐 회수 · THSR Taichung→Taoyuan · 23:10 TPE→AMS 직항",
    },
    {
      id: 4,
      date: "2026-09-05",
      weekday: "토요일",
      cities: "암스테르담 → 로테르담",
      lodging: "PREMIER SUITES Rotterdam",
      summary:
        "07:40 스키폴 도착 · Rotterdam Centraal 직통 · PREMIER SUITES 10:00~11:00 얼리체크인 요청 · Markthal·큐브하우스 · 13:00 일정 점검회의",
    },
    {
      id: 5,
      date: "2026-09-06",
      weekday: "일요일",
      cities: "로테르담·킨더다이크",
      lodging: "PREMIER SUITES Rotterdam",
      summary:
        "오전 향후 일정 점검 · 오후 Waterbus로 킨더다이크 · 무료 외부 동선 중심",
    },
    {
      id: 6,
      date: "2026-09-07",
      weekday: "월요일",
      cities: "로테르담·라이스베이크 → 함부르크",
      lodging: "Best Western Plus Hotel St. Raphael",
      summary:
        "Port of Rotterdam·ROG·TNO 회의 · 저녁 국제열차로 함부르크 이동 · Best Western Plus Hotel St. Raphael 예약숙박",
    },
    {
      id: 7,
      date: "2026-09-08",
      weekday: "화요일",
      cities: "함부르크",
      lodging: "Best Western Plus Hotel St. Raphael",
      summary:
        "OWC Germany 9/8 10:00 요청·Christian Apeah 참석 확정 · Skyborn Renewables 오후 · DNV는 9/9 오전으로 재배치",
    },
    {
      id: 8,
      date: "2026-09-09",
      weekday: "수요일",
      cities: "함부르크 → 에스비에르",
      lodging: "CABINN Plus Esbjerg",
      summary:
        "08:30 DNV Hamburg 미팅 권고안 · 10:53 ECE396 출발 · Kolding 환승 후 Esbjerg 14:54 도착",
    },
    {
      id: 9,
      date: "2026-09-10",
      weekday: "목요일",
      cities: "에스비에르 → 오르후스 → 코펜하겐",
      lodging: "CABINN Metro Copenhagen",
      summary:
        "Blue Water Shipping 회의 · 차량으로 Aarhus 이동 · 15:00 OWC Denmark 확정 미팅 · Aarhus H에서 저녁 열차로 코펜하겐 이동",
    },
    {
      id: 10,
      date: "2026-09-11",
      weekday: "금요일",
      cities: saving ? "코펜하겐 → 파리(CDG) → 인천" : "코펜하겐 → 이스탄불 → 인천",
      lodging: "기내박",
      summary: saving
        ? "10:10 CPH 출발 · AF1751→AF264 파리 1회 환승 · 9/12 09:35 인천 도착 · 운임 자동조회"
        : "10:25 CPH 출발 · TK1784→TK20 이스탄불 1회 환승 · 9/12 08:35 인천 도착 · TK20 출발시각 발권 전 재확인",
    },
    {
      id: 11,
      date: "2026-09-12",
      weekday: "토요일",
      cities: "인천",
      lodging: "귀가",
      summary: saving ? "09:35 인천 도착·입국" : "08:35 인천 도착·입국",
    },
  ];
}

function buildEvents(mode) {
  const saving = mode === "cost_optimized";
  const europeDeparture = [
        e(
          "d3-00",
          3,
          "07:30",
          "08:15",
          "조식·체크아웃·짐 보관",
          "숙박·출발준비",
          "CHECK Inn Taichung LaiLai, No.125 Sec.3 Sanmin Rd., Taichung",
          "도보",
          "45분",
          {
            official_url: "https://www.checkinn.com.tw/?page_id=22115",
            map_url: "https://www.google.com/maps/search/?api=1&query=CHECK+Inn+Taichung+LaiLai+No.125+Sec.3+Sanmin+Rd+Taichung",
            notes: "예약 안내상 9/4 11:00 이전 체크아웃. 오전 시내 일정 동안 수하물을 호텔에 맡긴 뒤 공항 이동 전 회수하는 동선.",
          },
        ),
    e(
          "d3-01",
          3,
          "08:30",
          "10:00",
          "National Taichung Theater·Calligraphy Greenway",
          "관광",
          "Taichung",
          "택시+도보",
          "90분",
          {
            official_url: "https://www.npac-ntt.org/en",
            map_url:
              "https://www.google.com/maps/search/?api=1&query=National+Taichung+Theater",
          },
        ),
        e(
          "d3-02",
          3,
          "10:20",
          "12:15",
          "Miyahara·타이중 구도심·점심·호텔 짐 회수",
          "관광·식사",
          "Miyahara → CHECK Inn Taichung LaiLai",
          "택시+도보",
          "1시간 55분",
          {
            map_url:
              "https://www.google.com/maps/dir/?api=1&origin=National+Taichung+Theater&destination=CHECK+Inn+Taichung+LaiLai+No.125+Sec.3+Sanmin+Rd+Taichung&waypoints=Miyahara+Taichung",
          },
        ),
        e(
          "d3-03",
          3,
          "12:15",
          "15:20",
          "CHECK Inn LaiLai → 타오위안공항",
          "교통",
          "CHECK Inn Taichung LaiLai → THSR Taichung → THSR Taoyuan → TPE",
          "택시+THSR+Airport MRT",
          "3시간 5분",
          {
            booking_url: "https://en.thsrc.com.tw/",
            min_cost_krw: 110_000,
            max_cost_krw: 180_000,
            cost_basis: "4인",
            notes: "THSR는 9/4(금) 공식 게시 시간표 확정. Airport MRT는 공식 사이트가 현재 8/31까지만 게시하여 9/4 편은 3일 전 재확인.",
            schedule_legs: [
              { status: "confirmed", service: "THSR 0826", from: "THSR Taichung", depart: "13:36", to: "THSR Taoyuan", arrive: "14:20", source_label: "THSR 공식 2026 시간표", source_url: "https://en.thsrc.com.tw/" },
              { status: "provisional", service: "Taoyuan Airport MRT", from: "A18 Taoyuan HSR", depart: "14:32 후보", to: "A12 Airport T1", arrive: "약 14:50", source_label: "Taoyuan Metro · 9/4 시간표 미공개", source_url: "https://www.tymetro.com.tw/tymetro-new/en/_pages/travel-guide/timetable-A18" },
            ],
          },
        ),
        e(
          "d3-04",
          3,
          "15:20",
          "20:00",
          "공항 라운지·출국수속·저녁",
          "출국",
          "Taoyuan International Airport T1",
          "도보",
          "4시간 40분",
        ),
        e(
          "d3-05",
          3,
          "23:10",
          "9/5 07:40",
          "TPE → AMS 직항",
          "항공",
          "Taipei → Amsterdam",
          "China Airlines",
          "14시간 30분",
          {
            booking_url: "https://www.google.com/travel/flights",
            notes:
              "비용 최적안보다 4인 약 190만원 높지만 환승과 약 8시간의 추가 이동을 제거.",
            schedule_legs: [
              { status: "confirmed", service: "China Airlines CI73", from: "TPE", depart: "23:10", to: "AMS", arrive: "9/5 07:40", source_label: "Google Flights 현재 판매편" },
            ],
          },
        ),
      ];

  return [
    e(
      "d1-01",
      1,
      "05:00",
      "07:00",
      "인천공항 집결·출국수속",
      "출국",
      "Incheon International Airport",
      "개별 이동",
      "2시간",
    ),
    e(
      "d1-02",
      1,
      "07:55",
      "09:40",
      "ICN → RMQ 직항",
      "항공",
      "Incheon → Taichung",
      "Jin Air",
      "2시간 45분",
      {
        booking_url: "https://www.google.com/travel/flights",
        notes: "출국일 2026-09-02 고정. LJ737 ICN 07:55→RMQ 09:40 현재 판매편 기준이며 운임은 Google Flights 4인 자동조회.",
        schedule_legs: [
          { status: "confirmed", service: "Jin Air LJ737", from: "ICN", depart: "07:55", to: "RMQ", arrive: "09:40", source_label: "Google Flights 현재 판매편" },
        ],
      },
    ),
    e(
      "d1-03",
      1,
      "09:40",
      "11:30",
      "입국·예약호텔 이동·짐 보관",
      "입국·교통",
      "RMQ → CHECK Inn Taichung LaiLai, No.125 Sec.3 Sanmin Rd., Taichung",
      "택시",
      "1시간 50분",
      {
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=Taichung+International+Airport&destination=CHECK+Inn+Taichung+LaiLai+No.125+Sec.3+Sanmin+Rd+Taichung",
        min_cost_krw: 35_000,
        max_cost_krw: 55_000,
        cost_basis: "차량 1대",
      },
    ),
    e(
      "d1-04",
      1,
      "11:30",
      "12:30",
      "타이중공원 산책·간단한 점심",
      "관광·식사",
      "Taichung Park",
      "도보",
      "60분",
      {
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Taichung+Park",
      },
    ),
    e(
      "d1-05",
      1,
      "12:30",
      "13:40",
      "호텔 → TIPC 타이중항만청",
      "교통",
      "No.2, Sec.10, Taiwan Blvd., Wuqi",
      "택시/기사차량",
      "약 70분",
      {
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=CHECK+Inn+Taichung+LaiLai+No.125+Sec.3+Sanmin+Rd+Taichung&destination=Port+of+Taichung+Taiwan+International+Ports+Corporation",
      },
    ),
    e(
      "d1-06",
      1,
      "14:10",
      "16:00",
      "TIPC 타이중항만청 회의",
      "업무",
      "No.2, Sec.10, Taiwan Blvd., Wuqi",
      "도보",
      "1시간 50분",
      {
        official_url: "https://tc.twport.com.tw/en",
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Port+of+Taichung+Taiwan+International+Ports+Corporation",
        notes: "대만 해상풍력 O&M 항만 운영·계획 논의.",
      },
    ),
    e(
      "d1-07",
      1,
      "16:10",
      "18:20",
      "우치어항·가오메이 습지 일몰",
      "관광·식사",
      "Wuqi Fishing Harbor → Gaomei Wetlands",
      "택시/기사차량",
      "2시간 10분",
      {
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=Port+of+Taichung&destination=Gaomei+Wetlands&waypoints=Wuqi+Fishing+Harbor",
        notes: "업무지 인접 무료 관광. 기상 악화 시 호텔 복귀.",
      },
    ),
    e(
      "d1-08",
      1,
      "18:20",
      "20:00",
      "가오메이 → CHECK Inn LaiLai·체크인",
      "교통·숙박",
      "CHECK Inn Taichung LaiLai, No.125 Sec.3 Sanmin Rd., Taichung",
      "택시/기사차량",
      "약 1시간 40분",
    ),
    e(
      "d2-01",
      2,
      "08:40",
      "10:10",
      "호텔 → VESTAS O&M Base",
      "교통",
      "No.45, Lugong Rd., Lukang",
      "기사차량",
      "약 90분",
      {
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=CHECK+Inn+Taichung+LaiLai+No.125+Sec.3+Sanmin+Rd+Taichung&destination=No.45+Lugong+Rd+Lukang",
      },
    ),
    e(
      "d2-02",
      2,
      "10:30",
      "13:30",
      "VESTAS O&M Base 현장견학·회의·중식",
      "업무",
      "CFXD & ZN Offshore Windfarm O&M Base",
      "도보",
      "3시간",
      {
        map_url:
          "https://www.google.com/maps/search/?api=1&query=24.0765986,120.3773545",
        notes: "터빈 O&M 기술·정비체계·예비품 운영 논의.",
      },
    ),
    e(
      "d2-03",
      2,
      "13:30",
      "15:30",
      "TIPC·VESTAS 회의결과 공유",
      "업무",
      "VESTAS O&M Base",
      "도보",
      "2시간",
      {
        notes: "해상풍력 O&M 인프라·요구조건 정리.",
      },
    ),
    e(
      "d2-04",
      2,
      "15:40",
      "17:10",
      "루강 옛거리·용산사",
      "관광",
      "Lukang Old Street",
      "기사차량+도보",
      "90분",
      {
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Lukang+Old+Street",
      },
    ),
    e(
      "d2-05",
      2,
      "17:10",
      "18:20",
      "루강 → 타이중 호텔",
      "교통",
      "Lukang → Taichung",
      "기사차량",
      "70분",
    ),
    e(
      "d2-06",
      2,
      "19:00",
      "20:30",
      "춘수이탕 저녁·버블티",
      "식사",
      "Chun Shui Tang Siwei Original Store",
      "택시",
      "90분",
      {
        official_url: "https://www.chunshuitang.com.tw/",
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Chun+Shui+Tang+Siwei+Original+Store",
      },
    ),
    ...europeDeparture,
    e(
      "d4-01",
      4,
      "07:40",
      "09:45",
      "스키폴 입국·로테르담 이동",
      "입국·교통",
      "AMS → Rotterdam Centraal",
      "NS Intercity Direct",
      "약 2시간",
      {
        booking_url: "https://www.nsinternational.com/en",
        notes: "Schiphol→Rotterdam 직통은 약 26~27분. 항공 도착·입국심사 변동 때문에 특정 편을 선결제하지 않고 입국 후 첫 가능한 NS 직통편을 탑승.",
        schedule_legs: [
          { status: "flexible", service: "NS Intercity Direct", from: "Schiphol Airport", depart: "입국 후 첫 가능편", to: "Rotterdam Centraal", arrive: "출발 + 약 26~27분", source_label: "NS Journey Planner" },
        ],
      },
    ),
    e(
      "d4-02",
      4,
      "09:45",
      "10:30",
      "PREMIER SUITES 도착·짐 보관·얼리 체크인 요청",
      "숙박",
      "PREMIER SUITES Rotterdam, Weena 710, 3014 DA Rotterdam",
      "도보",
      "45분",
      {
        official_url: "https://www.premiersuiteseurope.com/en/locations/the-netherlands/rotterdam/serviced-apartments-rotterdam",
        map_url: "https://www.google.com/maps/dir/?api=1&origin=Rotterdam+Centraal&destination=PREMIER+SUITES+Rotterdam+Weena+710&travelmode=walking",
        notes: "9/5~9/7 예약 숙소. 10:00~11:00 얼리 체크인을 요청했으며 '가능한 경우 제공' 상태라 확정 체크인 시간이 아님. 공식 기본 체크인은 15:00, 체크아웃은 11:00. 얼리 체크인 불가 시 1층 수하물 보관실에 짐을 맡기고 일정 진행.",
      },
    ),
    e(
      "d4-03",
      4,
      "10:45",
      "12:30",
      "Markthal·Cube Houses·Oude Haven",
      "관광·식사",
      "Rotterdam Centrum",
      "메트로+도보",
      "1시간 45분",
      {
        official_url: "https://www.markthal.nl/en/",
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=PREMIER+SUITES+Rotterdam+Weena+710&destination=Oude+Haven+Rotterdam&waypoints=Markthal+Rotterdam%7CCube+Houses",
        notes: "외부·시장 중심 저비용 동선.",
      },
    ),
    e(
      "d4-04",
      4,
      "13:00",
      "16:00",
      "네덜란드 일정 점검회의",
      "업무정리",
      "PREMIER SUITES Rotterdam co-working area 또는 Rotterdam Centraal 인근 업무공간",
      "도보",
      "3시간",
      { notes: "얼리 체크인 여부와 무관하게 진행 가능하도록 공식 co-working area 또는 중앙역 인근 업무공간을 사용. 객실 입실이 완료되면 객실에서 진행 가능." },
    ),
    e(
      "d4-05",
      4,
      "16:20",
      "19:30",
      "Delfshaven·Erasmusbrug·Bazar 저녁",
      "관광·식사",
      "Rotterdam",
      "트램+도보",
      "3시간 10분",
      {
        booking_url: "https://hotelbazar.nl/en/restaurant-bazar/",
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=Historic+Delfshaven&destination=Restaurant+Bazar+Rotterdam&waypoints=Erasmusbrug",
      },
    ),
    e(
      "d5-01",
      5,
      "08:00",
      "09:30",
      "조식·휴식",
      "개인정비",
      "PREMIER SUITES Rotterdam",
      "도보",
      "90분",
    ),
    e(
      "d5-02",
      5,
      "10:00",
      "12:00",
      "향후 일정 점검회의",
      "업무정리",
      "호텔 공용공간",
      "도보",
      "2시간",
    ),
    e(
      "d5-03",
      5,
      "12:20",
      "17:20",
      "WaterShuttle·킨더다이크 풍차군",
      "관광",
      "Rotterdam Erasmusbrug → Kinderdijk Molenkade",
      "WaterShuttle+도보",
      "5시간",
      {
        booking_url: "https://www.waterbus.nl/en/",
        official_url: "https://kinderdijk.com/",
        notes: "2026 여름 공식 시간표(3/23~10/5) 기준. 무료 외부 산책, 박물관 풍차 입장은 선택.",
        schedule_legs: [
          { status: "confirmed", service: "WaterShuttle", from: "Rotterdam Erasmusbrug", depart: "12:40", to: "Kinderdijk Molenkade", arrive: "13:10", source_label: "WaterShuttle 2026 summer timetable" },
          { status: "confirmed", service: "WaterShuttle", from: "Kinderdijk Molenkade", depart: "16:45", to: "Rotterdam Erasmusbrug", arrive: "17:15", source_label: "WaterShuttle 2026 summer timetable" },
        ],
      },
    ),
    e(
      "d5-04",
      5,
      "18:00",
      "19:30",
      "Fenix Food Factory·항만 저녁",
      "식사",
      "Katendrecht, Rotterdam",
      "메트로+도보",
      "90분",
      {
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Fenix+Food+Factory+Rotterdam",
      },
    ),
    e(
      "d6-01",
      6,
      "08:00",
      "08:50",
      "조식·체크아웃·짐 보관",
      "숙박",
      "PREMIER SUITES Rotterdam, Weena 710, 3014 DA Rotterdam",
      "도보",
      "50분",
    ),
    e(
      "d6-02",
      6,
      "08:50",
      "09:20",
      "호텔 → Port of Rotterdam Authority",
      "교통",
      "Wilhelminakade 909, Rotterdam",
      "택시",
      "30분",
      {
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=PREMIER+SUITES+Rotterdam+Weena+710&destination=Wilhelminakade+909+Rotterdam",
      },
    ),
    e(
      "d6-03",
      6,
      "09:20",
      "11:30",
      "Port of Rotterdam Authority 회의",
      "업무",
      "World Port Center, Wilhelminakade 909",
      "도보",
      "2시간 10분",
      {
        official_url: "https://www.portofrotterdam.com/en",
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Wilhelminakade+909+Rotterdam",
        notes: "해상풍력 O&M 항만 추진·운영계획.",
      },
    ),
    e(
      "d6-04",
      6,
      "11:30",
      "12:25",
      "점심·ROG 이동",
      "식사·교통",
      "Wilhelminaplein → Drutenstraat 7",
      "택시",
      "55분",
    ),
    e(
      "d6-05",
      6,
      "12:25",
      "14:10",
      "Rotterdam Offshore Group 현장견학",
      "업무",
      "Drutenstraat 7, 3087 CC Rotterdam",
      "도보",
      "1시간 45분",
      {
        official_url: "https://www.rotterdamoffshore.com/",
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Rotterdam+Offshore+Group+Drutenstraat+7",
        notes: "선박·풍력설비 수리·정비 작업 수행체계.",
      },
    ),
    e(
      "d6-06",
      6,
      "14:10",
      "15:00",
      "ROG → TNO Rijswijk",
      "교통",
      "Drutenstraat 7 → Kesslerpark 1",
      "택시",
      "50분",
      {
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=Drutenstraat+7+Rotterdam&destination=Kesslerpark+1+Rijswijk",
      },
    ),
    e(
      "d6-07",
      6,
      "15:00",
      "16:30",
      "TNO Rijswijk 회의",
      "업무",
      "Kesslerpark 1, 2288 GS Rijswijk",
      "도보",
      "90분",
      {
        official_url:
          "https://www.tno.nl/en/about-tno/contact/locations/rijswijk-kesslerpark/",
        map_url:
          "https://www.google.com/maps/search/?api=1&query=TNO+Kesslerpark+1+Rijswijk",
        notes: "해상풍력 O&M 로봇점검·자동화 기술.",
      },
    ),
    e(
      "d6-08",
      6,
      "16:30",
      "17:05",
      "TNO → PREMIER SUITES 짐 회수 → 로테르담 중앙역",
      "교통",
      "TNO Kesslerpark 1 → PREMIER SUITES Rotterdam, Weena 710 → Rotterdam Centraal",
      "택시+도보",
      "35분",
    ),
    e(
      "d6-09",
      6,
      "17:20",
      "23:16",
      "로테르담 → 함부르크",
      "교통",
      "Rotterdam Centraal → Hamburg Hbf",
      "NS/DB 국제열차",
      "약 5시간 56분",
      {
        booking_url:
          "https://www.nsinternational.com/en/germany/train-hamburg",
        official_url: "https://int.bahn.de/en",
        original_currency: "EUR",
        original_min: 33,
        original_max: 80,
        min_cost_krw: 210_000,
        max_cost_krw: 500_000,
        cost_basis: "4인·조기예약",
        notes:
          "2026 현행 DB/NS 시간표 패턴의 저녁 연결편. 9/7 공사·편성 변경 가능성이 있어 발권 화면에서 최종 재확인해야 하며, 확정 전까지는 '시간표 후보'로 표시.",
        schedule_legs: [
          { status: "provisional", service: "IC 2863 · IC 1765 · ICE 243 · ICE 104", from: "Rotterdam Centraal", depart: "17:20 후보", to: "Hamburg Hbf", arrive: "23:16 후보", source_label: "2026 DB/NS 현행 시간표 패턴 · 9/7 재확인" },
        ],
      },
    ),
    e(
      "d6-10",
      6,
      "23:16",
      "23:30",
      "함부르크 중앙역 → 예약호텔",
      "교통·숙박",
      "Hamburg Hbf → Best Western Plus Hotel St. Raphael, Adenauerallee 41, 20097 Hamburg",
      "도보/택시",
      "약 10~15분 버퍼",
      {
        booking_url: "https://www.booking.com/hotel/de/straphaelbestwesternhh.html",
        map_url: "https://www.google.com/maps/dir/?api=1&origin=Hamburg+Hbf&destination=Best+Western+Plus+Hotel+St+Raphael+Adenauerallee+41+Hamburg&travelmode=walking",
        notes: "9/7 체크인 15:00 이후 가능. 심야 도착 예정이므로 예약 유지·늦은 체크인 가능 여부를 Booking.com 메시지 또는 호텔에 사전 통지 권고.",
      },
    ),
    e(
      "d7-01",
      7,
      "07:30",
      "09:10",
      "조식·OWC·Skyborn 미팅 준비",
      "업무준비",
      "Best Western Plus Hotel St. Raphael, Adenauerallee 41, 20097 Hamburg",
      "도보",
      "1시간 40분",
      {
        booking_url: "https://www.booking.com/hotel/de/straphaelbestwesternhh.html",
        notes: "예약호텔에서 OWC·Skyborn 질의사항 최종 점검. OWC Hamburg는 Christian Apeah 참석 확정, 9/8 10:00 요청, 장소는 사무실 이전으로 확정 대기.",
      },
    ),
    e(
      "d7-02",
      7,
      "09:10",
      "09:50",
      "OWC Germany 미팅 이동버퍼",
      "교통·업무준비",
      "Best Western Plus Hotel St. Raphael → Hamburg OWC 지정 미팅 장소(확정 대기)",
      "택시/대중교통",
      "40분 가예약",
      {
        map_url: "https://www.google.com/maps/search/?api=1&query=Best+Western+Plus+Hotel+St+Raphael+Adenauerallee+41+Hamburg",
        notes: "OWC의 실제 미팅 장소가 확정되지 않아 허위 경로를 생성하지 않음. 장소 회신 즉시 호텔 출발시간과 상세경로를 재계산.",
      },
    ),
    e(
      "d7-03",
      7,
      "10:00",
      "11:30",
      "OWC Germany 기술미팅 (9/8 10:00 요청·참석자 확정)",
      "업무",
      "Hamburg · OWC 지정 미팅 장소(사무실 이전으로 조율중)",
      "미정",
      "90분 계획",
      {
        official_url: "https://owcltd.com/our-people/",
        map_url: "https://www.google.com/maps/search/?api=1&query=Hamburg+Germany",
        meeting_status: "Christian Apeah 참석 확정 / 9/8 10:00 요청 / 장소 확정 대기",
        attendees: ["Christian Apeah · Global Head of Independent Engineering · 기술실사/Lender’s Technical Advisory 부문장"],
        meeting_agenda: [
          "독일 해상풍력 Independent Engineering 및 기술실사 수행 사례",
          "Lender’s Technical Advisory·Owner’s Engineering 수행사례",
          "개발·설계·건설·운영 단계의 주요 Technical Risk 관리",
          "WTG·Foundation·Cable·Offshore Substation 주요 패키지 기술검토",
          "설계 최적화 및 사업비·LCoE 절감 Engineering Approach",
          "국내 해상풍력 사업 적용 시사점",
        ],
        notes: "9/8 오전 10시 미팅을 요청한 최신 조율내용 반영. Christian Apeah 참석은 확정됐으며, OWC Hamburg 사무실 이전으로 장소는 회신 대기. 종료시각 11:30은 90분 미팅 계획값.",
      },
    ),
    e(
      "d7-04",
      7,
      "11:30",
      "12:50",
      "OWC 미팅 정리·점심·Skyborn 이동",
      "업무정리·식사·교통",
      "OWC 지정 장소(미정) → HafenCity → Skyborn Renewables, Ericusspitze 2-4",
      "택시/도보",
      "1시간 20분",
      {
        map_url: "https://www.google.com/maps/search/?api=1&query=Skyborn+Renewables+Ericusspitze+2-4+Hamburg",
        notes: "OWC 장소가 미정이므로 목적지 Skyborn만 확정 표시. OWC 장소 확정 후 실제 점심·이동경로를 자동 재산정.",
      },
    ),
    e(
      "d7-05",
      7,
      "13:00",
      "14:30",
      "Skyborn Renewables 해상풍력 사업개발 미팅 (요청 중)",
      "업무",
      "Skyborn Renewables GmbH, Ericusspitze 2-4, 20457 Hamburg",
      "도보",
      "90분",
      {
        official_url: "https://www.skybornrenewables.com/contact",
        map_url: "https://www.google.com/maps/search/?api=1&query=Skyborn+Renewables+Ericusspitze+2-4+Hamburg",
        meeting_status: "Skyborn Hamburg 9/8 오후 요청·시간 확정 대기",
        notes: "유럽 해상풍력 사업개발 경험, 주요 추진사례, 개발·추진과정 이슈와 대응 경험, 국내 사업 적용 시사점 중심.",
      },
    ),
    e(
      "d7-055",
      7,
      "14:30",
      "15:00",
      "Skyborn 미팅 정리·예약호텔 복귀",
      "업무정리·교통",
      "Skyborn Renewables, Ericusspitze 2-4 → Best Western Plus Hotel St. Raphael, Adenauerallee 41",
      "택시/대중교통",
      "30분 버퍼",
      {
        sort_order: 55,
        map_url: "https://www.google.com/maps/dir/?api=1&origin=Skyborn+Renewables+Ericusspitze+2-4+Hamburg&destination=Best+Western+Plus+Hotel+St+Raphael+Adenauerallee+41+Hamburg&travelmode=transit",
        notes: "Skyborn 종료 후 호텔 복귀해 회의내용을 정리하고 다음날 DNV 질의사항 준비.",
      },
    ),
    e(
      "d7-06",
      7,
      "15:00",
      "16:30",
      "OWC·Skyborn 결과정리·DNV 사전준비",
      "업무정리",
      "Best Western Plus Hotel St. Raphael",
      "도보",
      "90분",
      {
        notes: "OWC Independent Engineering/LTA와 Skyborn 사업개발 내용을 기관별 보고서 메모로 정리하고 9/9 DNV Digital Twin·인증 질의사항을 최종 정리.",
      },
    ),
    e(
      "d7-07",
      7,
      "16:30",
      "20:30",
      "Elbphilharmonie·Landungsbrücken·저녁",
      "관광·식사",
      "Best Western Plus Hotel St. Raphael → Elbphilharmonie → Landungsbrücken",
      "U-Bahn/도보",
      "4시간",
      {
        booking_url: "https://www.elbphilharmonie.de/en/plaza-tickets",
        map_url: "https://www.google.com/maps/dir/?api=1&origin=Best+Western+Plus+Hotel+St+Raphael+Adenauerallee+41+Hamburg&destination=Landungsbrucken+Hamburg&waypoints=Elbphilharmonie+Hamburg&travelmode=transit",
        route_detail: ["Best Western Plus Hotel St. Raphael", "Hamburg Hbf/대중교통", "Elbphilharmonie", "Landungsbrücken"],
      },
    ),
    e(
      "d8-01",
      8,
      "07:15",
      "08:10",
      "조식·체크아웃·호텔에 짐 임시보관",
      "숙박·업무준비",
      "Best Western Plus Hotel St. Raphael, Adenauerallee 41, 20097 Hamburg",
      "도보",
      "55분",
      {
        booking_url: "https://www.booking.com/hotel/de/straphaelbestwesternhh.html",
        notes: "9/9 체크아웃은 12:00까지 가능하나 10:53 국제열차 때문에 조기 체크아웃. DNV 방문 중 수하물은 호텔에 맡기고 복귀 시 회수하는 동선.",
      },
    ),
    e(
      "d8-011",
      8,
      "08:10",
      "08:25",
      "예약호텔 → DNV Hamburg 이동",
      "교통",
      "Best Western Plus Hotel St. Raphael, Adenauerallee 41 → DNV, Brooktorkai 18, 20457 Hamburg",
      "택시",
      "15분 버퍼",
      {
        sort_order: 11,
        map_url: "https://www.google.com/maps/dir/?api=1&origin=Best+Western+Plus+Hotel+St+Raphael+Adenauerallee+41+Hamburg&destination=DNV+Brooktorkai+18+Hamburg&travelmode=driving",
        route_detail: ["Best Western Plus Hotel St. Raphael · Adenauerallee 41", "DNV Hamburg · Brooktorkai 18"],
      },
    ),
    e(
      "d8-012",
      8,
      "08:30",
      "09:40",
      "DNV Hamburg 해상풍력 기술미팅 (9/9 오전 권고안)",
      "업무",
      "DNV Hamburg Office, Brooktorkai 18, 20457 Hamburg",
      "도보",
      "70분 권고",
      {
        sort_order: 12,
        official_url: "https://www.dnv.com/contact/digital-solutions/",
        map_url: "https://www.google.com/maps/search/?api=1&query=DNV+Brooktorkai+18+20457+Hamburg",
        meeting_status: "9/9 08:30~09:40 권고안·DNV 회신 대기",
        meeting_agenda: [
          "유럽 해상풍력 사업 추진사례 및 주요 기술동향",
          "Digital Twin의 설계·건설·운영 적용",
          "운영데이터 연계·상태 모니터링·O&M 최적화",
          "해상풍력 프로젝트 인증 및 설계·제작·시공 기술검증",
          "개발·건설·운영 단계의 주요 기술리스크와 대응",
          "국내 해상풍력 사업 적용 시 인증·기술요건",
        ],
        notes: "OWC가 9/8 10:00로 조율되면서 DNV를 9/9 오전으로 재배치한 동선 권고안. 10:53 Hamburg Hbf ECE396을 지키기 위해 09:40 종료 기준.",
      },
    ),
    e(
      "d8-013",
      8,
      "09:40",
      "10:20",
      "DNV → 예약호텔 짐 회수 → Hamburg Hbf",
      "교통",
      "DNV Brooktorkai 18 → Best Western Plus Hotel St. Raphael, Adenauerallee 41 → Hamburg Hbf",
      "택시+도보",
      "40분 버퍼",
      {
        sort_order: 13,
        map_url: "https://www.google.com/maps/dir/?api=1&origin=DNV+Brooktorkai+18+Hamburg&destination=Hamburg+Hbf&waypoints=Best+Western+Plus+Hotel+St+Raphael+Adenauerallee+41+Hamburg&travelmode=driving",
        route_detail: ["DNV · Brooktorkai 18", "Best Western Plus Hotel St. Raphael · 짐 회수", "Hamburg Hbf"],
        notes: "10:20 Hbf 도착 목표로 10:53 ECE396 탑승까지 약 30분 이상 승차버퍼 확보.",
      },
    ),
    e(
      "d8-02",
      8,
      "10:53",
      "14:54",
      "함부르크 → 에스비에르",
      "교통",
      "Hamburg Hbf → Kolding → Esbjerg",
      "DB/DSB 열차",
      "4시간 1분",
      {
        booking_url: "https://int.bahn.de/en",
        original_currency: "EUR",
        original_min: 35,
        original_max: 70,
        min_cost_krw: 220_000,
        max_cost_krw: 450_000,
        cost_basis: "4인·조기예약",
        notes:
          "Rejseplanen/DSB가 2026년 9월 운행기간을 게시한 연결편 기준. Kolding 환승 22분.",
        schedule_legs: [
          { status: "confirmed", service: "ECE 396", from: "Hamburg Hbf", depart: "10:53", to: "Kolding St.", arrive: "13:44", source_label: "Rejseplanen/DSB 2026 게시 시간표" },
          { status: "confirmed", service: "IC 2340", from: "Kolding St.", depart: "14:06", to: "Esbjerg St.", arrive: "14:54", source_label: "Rejseplanen/DSB 2026 게시 시간표" },
        ],
      },
    ),
    e(
      "d8-03",
      8,
      "14:54",
      "15:30",
      "호텔 이동·체크인",
      "숙박",
      "CABINN Plus Esbjerg, Torvegade 27",
      "도보",
      "36분",
    ),
    e(
      "d8-04",
      8,
      "15:45",
      "18:30",
      "Men at Sea·Fisheries and Maritime Museum 외부",
      "관광",
      "Sædding Strand, Esbjerg",
      "버스+도보",
      "2시간 45분",
      {
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Men+at+Sea+Esbjerg",
        notes: "Men at Sea 외부 관람 무료.",
      },
    ),
    e(
      "d8-05",
      8,
      "19:00",
      "20:30",
      "Esbjerg Street Food 저녁",
      "식사",
      "Kongensgade, Esbjerg",
      "도보",
      "90분",
      {
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Esbjerg+Street+Food",
      },
    ),
    e(
      "d9-01",
      9,
      "07:30",
      "09:05",
      "조식·체크아웃·짐 동반 출발 준비",
      "숙박·업무준비",
      "CABINN Plus Esbjerg, Torvegade 27, 6700 Esbjerg",
      "도보",
      "1시간 35분",
      {
        notes: "OWC Denmark 미팅 장소가 Aarhus로 확정되어 호텔 재방문 없이 짐을 동반해 Blue Water Shipping으로 이동하도록 변경.",
      },
    ),
    e(
      "d9-02",
      9,
      "09:05",
      "09:25",
      "CABINN Plus → Blue Water Shipping 이동",
      "교통",
      "CABINN Plus Esbjerg → Blue Water Shipping, Trafikhavnskaj 9, 6700 Esbjerg",
      "택시/기사차량",
      "20분",
      {
        map_url: "https://www.google.com/maps/dir/?api=1&origin=CABINN+Plus+Esbjerg+Torvegade+27&destination=Blue+Water+Shipping+Trafikhavnskaj+9+Esbjerg&travelmode=driving",
        notes: "짐을 차량에 동반. Blue Water Shipping 공식 Esbjerg 본사 주소 Trafikhavnskaj 9 기준.",
      },
    ),
    e(
      "d9-03",
      9,
      "09:30",
      "11:30",
      "Blue Water Shipping 회의",
      "업무",
      "Blue Water Shipping A/S, Trafikhavnskaj 9, 6700 Esbjerg",
      "도보",
      "2시간",
      {
        official_url: "https://www.bws.net/contact/denmark/esbjerg",
        map_url: "https://www.google.com/maps/search/?api=1&query=Blue+Water+Shipping+Trafikhavnskaj+9+6700+Esbjerg",
        notes: "해상풍력 터빈 공급망·운송·보관·통관·Port Service 및 해상풍력 물류 수행체계 논의.",
      },
    ),
    e(
      "d9-04",
      9,
      "11:30",
      "13:30",
      "Blue Water Shipping → Aarhus 이동",
      "교통",
      "Trafikhavnskaj 9, Esbjerg → Kolding → Vejle → Horsens → Banegårdspladsen 4, 8000 Aarhus C",
      "전용차량/대형택시",
      "최대 약 2시간",
      {
        map_url: "https://www.google.com/maps/dir/?api=1&origin=Blue+Water+Shipping+Trafikhavnskaj+9+Esbjerg&destination=Banegardspladsen+4+8000+Aarhus+C&waypoints=Kolding|Vejle|Horsens&travelmode=driving",
        notes: "OWC 측 안내 최대 약 2시간을 기준으로 차량 이동. 4인+수하물이므로 당일 전용차량 또는 대형택시 사전예약 권고. E20→E45 축으로 이동하고 점심은 도착 후 진행.",
        route_detail: ["Blue Water Shipping · Trafikhavnskaj 9", "E20 · Kolding 방면", "E45 · Vejle", "E45 · Horsens", "OWC Denmark · Banegårdspladsen 4, Aarhus"],
      },
    ),
    e(
      "d9-05",
      9,
      "13:30",
      "14:45",
      "Aarhus 도착·점심·OWC 미팅 준비",
      "식사·업무준비",
      "Banegårdspladsen / Aarhus H 일대, 8000 Aarhus C",
      "도보",
      "1시간 15분",
      {
        map_url: "https://www.google.com/maps/search/?api=1&query=Banegardspladsen+4+8000+Aarhus+C",
        notes: "15:00 확정 미팅 전 30분 이상 도착 버퍼 확보. OWC 사무실이 Aarhus H 바로 앞 Banegårdspladsen에 있어 미팅 후 철도 환승에도 유리.",
      },
    ),
    e(
      "d9-055",
      9,
      "15:00",
      "16:30",
      "OWC Denmark 해상풍력 기술미팅 (15:00 확정)",
      "업무",
      "OWC Denmark, Banegårdspladsen 4, 2. sal th, 8000 Aarhus C, Denmark",
      "도보",
      "90분 계획",
      {
        sort_order: 55,
        official_url: "https://owcltd.com/offices/aarhus-2/",
        map_url: "https://www.google.com/maps/search/?api=1&query=OWC+Banegardspladsen+4+8000+Aarhus+C+Denmark",
        meeting_status: "9/10 15:00·Aarhus 주소·참석자 확정 / 종료시각 16:30은 출장 동선상 계획값",
        attendees: ["René Aagaard · Country Manager, OWC Denmark", "Rune Nørgaard · Deputy Country Manager, OWC Denmark"],
        meeting_agenda: [
          "덴마크 및 북해 해상풍력 Owner’s Engineering·Technical Advisory 수행 사례",
          "개발 초기 Technical Risk·설계 의사결정 관리",
          "WTG·Foundation·Cable·Offshore Substation 패키지 기술검토",
          "Engineering 최적화 및 사업비·LCoE 절감",
          "Asset Management 및 BoP O&M 기술지원 사례",
          "덴마크 WTG 설치·운영·최적화 및 공급망·항만 인프라 대응 경험",
          "독일 대비 덴마크 해상풍력 시장·프로젝트 환경 차이와 국내 적용 시사점",
        ],
        notes: "미팅 시작 15:00, 장소와 참석자 확정. René Aagaard(Country Manager), Rune Nørgaard(Deputy Country Manager) 참석. 종료시각은 회신에 명시되지 않아 90분을 계획값으로 두고 후속 Aarhus H 열차와 연계.",
      },
    ),
    e(
      "d9-06",
      9,
      "16:30",
      "17:05",
      "OWC 미팅 정리·Aarhus H 이동·승차 준비",
      "업무정리·교통",
      "OWC Denmark, Banegårdspladsen 4 → Aarhus H",
      "도보",
      "35분",
      {
        map_url: "https://www.google.com/maps/dir/?api=1&origin=Banegardspladsen+4+8000+Aarhus+C&destination=Aarhus+H&travelmode=walking",
        notes: "OWC 사무실은 Aarhus H 전면 Banegårdspladsen에 위치. 미팅 종료 직후 핵심내용 메모 후 승강장 이동.",
      },
    ),
    e(
      "d9-07",
      9,
      "17:20",
      "20:36",
      "Aarhus → Copenhagen",
      "교통",
      "Aarhus H → Skanderborg → Horsens → Vejle → Fredericia → Odense → Ringsted → København H",
      "DSB InterCityLyn",
      "3시간 16분 후보",
      {
        booking_url: "https://www.dsb.dk/en/",
        map_url: "https://www.google.com/maps/dir/?api=1&origin=Aarhus+H&destination=Kobenhavn+H&waypoints=Skanderborg+Station|Horsens+Station|Vejle+Station|Fredericia+Station|Odense+Station|Ringsted+Station&travelmode=transit",
        min_cost_krw: 320_000,
        max_cost_krw: 600_000,
        cost_basis: "4인·Orange/일반 운임",
        notes: "현재 Rejseplanen K26 패턴상 ICL 50058이 Aarhus H 17:20→København H 20:36. 다만 9/7~9/11 선로공사·일자별 예외가 있어 9/10 실제 운행 여부와 편명은 출발 3일 전 재확인. 미팅이 16:30 종료된다는 계획값 기준 50분 버퍼.",
        route_detail: ["Aarhus H", "Skanderborg St.", "Horsens St.", "Vejle St.", "Fredericia St.", "Odense St.", "Ringsted St.", "København H"],
        schedule_legs: [
          { status: "provisional", service: "DSB ICL 50058 후보", from: "Aarhus H", depart: "17:20 후보", to: "København H", arrive: "20:36 후보", source_label: "Rejseplanen K26 현행 패턴 · 9/10 선로공사/일자별 예외 3일 전 재확인" },
        ],
      },
    ),
    e(
      "d9-08",
      9,
      "20:36",
      "22:00",
      "København H → CABINN Metro 체크인·간단한 저녁",
      "교통·숙박·식사",
      "København H → Ørestad St. → CABINN Metro, Arne Jacobsens Allé 2",
      "지역열차+도보",
      "1시간 24분",
      {
        booking_url: "https://en.cabinn.com/hotel/cabinn-metro",
        map_url: "https://www.google.com/maps/dir/?api=1&origin=Kobenhavn+H&destination=CABINN+Metro+Arne+Jacobsens+Alle+2&waypoints=Orestad+Station&travelmode=transit",
        notes: "Aarhus발 열차 도착 후 Ørestad 방면 첫 적정 지역열차 이용. 9/7~9/12 선로공사 때문에 현지 연결편은 3일 전 재확인하고, 지연 시 København H→호텔 택시로 대체.",
        route_detail: ["København H", "Ørestad St.", "CABINN Metro"],
      },
    ),
    ...(saving
      ? [
          e("d10c-01",10,"07:10","07:50","체크아웃·코펜하겐공항 이동","출국·교통","CABINN Metro → Ørestad St. → CPH","도보+지역열차","40분",{notes:"Rejseplanen은 9/7~9/12 선로공사로 일부 열차 변경 가능성을 공지. 3일 전 재확인하고 변경 시 택시로 대체.",schedule_legs:[{status:"provisional",service:"Regional train Re 1026 후보",from:"Ørestad St.",depart:"07:37 후보",to:"CPH Lufthavn",arrive:"07:44 후보",source_label:"Rejseplanen 현행 패턴 · 9/11 선로공사 재확인"}]}),
          e("d10c-02",10,"10:10","12:10","CPH → CDG","항공","Copenhagen → Paris CDG","Air France","2시간",{booking_url:"https://www.google.com/travel/flights",notes:"귀국일정 경계 고정: 2026-09-11 CPH 출발 → 2026-09-12 ICN 입국. 운임은 Google Flights 자동조회.",schedule_legs:[{status:"confirmed",service:"Air France AF1751",from:"CPH",depart:"10:10",to:"CDG",arrive:"12:10",source_label:"Google Flights 현재 판매편"}]}),
          e("d10c-03",10,"12:10","14:40","파리 샤를드골 환승","환승","Paris Charles de Gaulle Airport","공항 내 이동","2시간 30분"),
          e("d10c-04",10,"14:40","9/12 09:35","CDG → ICN","항공","Paris CDG → Incheon","Air France","11시간 55분",{booking_url:"https://www.google.com/travel/flights",notes:"CPH→CDG→ICN 연결발권. 2026-09-12 09:35 ICN 입국일 고정이며 가격 비교는 최신 자동조회값을 사용.",schedule_legs:[{status:"confirmed",service:"Air France AF264",from:"CDG",depart:"14:40",to:"ICN",arrive:"9/12 09:35",source_label:"Google Flights 현재 판매편"}]}),
          e("d11-01",11,"09:35","10:35","인천 도착·입국","귀국","Incheon International Airport","도보","60분"),
        ]
      : [
          e("d10-01",10,"07:10","07:50","체크아웃·코펜하겐공항 이동","출국·교통","CABINN Metro → Ørestad St. → CPH","도보+지역열차","40분",{notes:"Rejseplanen은 9/7~9/12 선로공사로 일부 열차 변경 가능성을 공지. 3일 전 재확인하고 변경 시 택시로 대체.",schedule_legs:[{status:"provisional",service:"Regional train Re 1026 후보",from:"Ørestad St.",depart:"07:37 후보",to:"CPH Lufthavn",arrive:"07:44 후보",source_label:"Rejseplanen 현행 패턴 · 9/11 선로공사 재확인"}]}),
          e("d10-02",10,"10:25","14:45","CPH → IST","항공","Copenhagen → Istanbul","Turkish Airlines","3시간 20분",{booking_url:"https://www.google.com/travel/flights",schedule_legs:[{status:"confirmed",service:"Turkish Airlines TK1784",from:"CPH",depart:"10:25",to:"IST",arrive:"14:45",source_label:"Google Flights 현재 판매편"}]}),
          e("d10-03",10,"14:45","17:00","이스탄불 환승","환승","Istanbul Airport","공항 내 이동","2시간 15분"),
          e("d10-04",10,"17:00","9/12 08:35","IST → ICN","항공","Istanbul → Incheon","Turkish Airlines","9시간 35분",{booking_url:"https://www.google.com/travel/flights",notes:"9/12 08:35 ICN 도착 비교안. TK20 출발시각은 날짜별 판매화면과 계절운항표에 10분 차이가 있어 발권 직전 재확인.",schedule_legs:[{status:"confirmed",service:"Turkish Airlines TK20",from:"IST",depart:"17:00 판매화면 / 정규표 16:50",to:"ICN",arrive:"9/12 08:35",source_label:"Google Flights 날짜별 판매편 + TK20 계절운항표 · 발권 전 최종 재확인"}]}),
          e("d11-01",11,"08:35","09:35","인천 도착·입국","귀국","Incheon International Airport","도보","60분"),
        ]),
  ];
}

function buildFlights(mode) {
  const saving = mode === "cost_optimized";
  return [
    {
      id: "f1",
      day_id: 1,
      date: "2026-09-02",
      flight_no: "LJ737 직항",
      origin: "ICN",
      destination: "RMQ",
      depart_time: "07:55",
      arrive_time: "09:40",
      min_krw: null,
      max_krw: null,
      status: "출국일 고정·현재 판매편",
      alternative: "ICN→TPE 후 THSR는 현재 더 비쌈",
      url: "https://www.jinair.com/",
      notes: "2026-09-02 출국일 고정 · LJ737 07:55 ICN → 09:40 RMQ",
      sort_order: 10,
    },
    {
      id: "f2",
      day_id: 3,
      date: "2026-09-04",
      flight_no: "CI73 직항",
      origin: "TPE",
      destination: "AMS",
      depart_time: "23:10",
      arrive_time: "07:40+1",
      min_krw: null,
      max_krw: null,
      status: "직항·권고",
      alternative: "TPE 출발 다른 유럽 경유편은 필요 시 별도 비교",
      url: "https://www.china-airlines.com/",
      notes: "TPE→AMS 직항으로 환승 없이 이동",
      sort_order: 20,
    },
    saving
      ? {
          id: "f3", day_id: 10, date: "2026-09-11", flight_no: "AF1751 + AF264",
          origin: "CPH", destination: "ICN", depart_time: "10:10", arrive_time: "09:35+1",
          min_krw: null, max_krw: null, status: "귀국일 고정·CDG 1회 환승",
          alternative: "SAS 직항 및 다른 1회 경유편은 최신 자동운임으로 비교", url: "https://wwws.airfrance.co.kr/",
          notes: "AF1751 + AF264 · 9/11 10:10 CPH 출발 · 9/12 09:35 ICN 도착. 운임은 자동조회값 사용.", sort_order: 30,
        }
      : {
          id: "f3", day_id: 10, date: "2026-09-11", flight_no: "TK1784 + TK20",
          origin: "CPH", destination: "ICN", depart_time: "10:25", arrive_time: "08:35+1",
          min_krw: null, max_krw: null, status: "IST 1회 환승·TK20 시각 재확인",
          alternative: "Air France CDG 경유 비용안과 최신 자동운임 비교", url: "https://www.turkishairlines.com/",
          notes: "TK1784 + TK20 · 9/11 CPH 출발 · 9/12 08:35 ICN 도착. TK20 출발시각은 발권 직전 재확인.", sort_order: 30,
        },
  ];
}

const hotels = [
  {
    id: "h1",
    day_id: 1,
    name: "CHECK Inn Taichung LaiLai",
    city: "Taichung",
    check_in: "2026-09-02",
    check_out: "2026-09-04",
    nights: 2,
    rooms: null,
    min_krw: null,
    max_krw: null,
    status: "예약확정·16:00 이후 체크인",
    alternative: "",
    url: "https://www.checkinn.com.tw/?page_id=22115",
    notes: "예약자 Seungtaek Song · 2026-09-02부터 2박 · 체크인 16:00 이후 · 2026-09-04 11:00 이전 체크아웃 · 유료 조기 체크인/연장 서비스는 당일 현장 확인. 주소: No.125, Sec. 3, Sanmin Rd., North Dist., Taichung City 404. 객실 수·예약 인원·결제금액은 제공자료에 없어 임의 입력하지 않음.",
    sort_order: 10,
  },
  {
    id: "h2",
    day_id: 4,
    name: "PREMIER SUITES Rotterdam · Weena 710",
    city: "Rotterdam",
    check_in: "2026-09-05",
    check_out: "2026-09-07",
    nights: 2,
    rooms: null,
    min_krw: null,
    max_krw: null,
    status: "예약숙소·10:00~11:00 얼리체크인 요청(가용 시)",
    alternative: "",
    url: "https://www.premiersuiteseurope.com/en/locations/the-netherlands/rotterdam/serviced-apartments-rotterdam",
    notes: "Weena 710, 3014 DA Rotterdam · 9/5~9/7. 숙소 메시지상 10:00~11:00 체크인 요청은 가능한 경우 제공. 공식 기본 체크인 15:00·체크아웃 11:00·24시간 리셉션·수하물 보관 가능. 12:00 이전 얼리체크인은 공식 FAQ상 가용 시 가능하며 €25가 부과될 수 있음. 전달자료에는 객실 수·예약 인원·결제금액이 없어 임의 입력하지 않음.",
    sort_order: 20,
  },
  {
    id: "h3",
    day_id: 6,
    name: "Best Western Plus Hotel St. Raphael",
    city: "Hamburg",
    check_in: "2026-09-07",
    check_out: "2026-09-09",
    nights: 2,
    rooms: 3,
    min_krw: null,
    max_krw: null,
    status: "예약확정·체크인 현장결제",
    alternative: "",
    url: "https://www.booking.com/hotel/de/straphaelbestwesternhh.html",
    notes: "Adenauerallee 41, St. Georg, 20097 Hamburg · 체크인 9/7 15:00부터 · 체크아웃 9/9 12:00까지 · 2박/객실 3개 · Booking.com 예약 인원은 성인 3명으로 표시되어 출장자 4명과 1명 차이가 있으므로 인원 정정 또는 호텔 확인 필요 · 선결제 불필요, 체크인 시 결제.",
    sort_order: 30,
  },
  {
    id: "h4",
    day_id: 8,
    name: "CABINN Plus Esbjerg",
    city: "Esbjerg",
    check_in: "2026-09-09",
    check_out: "2026-09-10",
    nights: 1,
    rooms: 2,
    min_krw: 350_000,
    max_krw: 500_000,
    status: "최저가추천",
    alternative: "Hotel Ansgar",
    url: "https://en.cabinn.com/hotel/cabinn-esbjerg-plus",
    notes:
      "공식 시작가 DKK875/실·박. Hotel Britannia보다 저렴하고 Blue Water Shipping 택시 약 10분.",
    sort_order: 40,
  },
  {
    id: "h5",
    day_id: 9,
    name: "CABINN Metro",
    city: "Copenhagen",
    check_in: "2026-09-10",
    check_out: "2026-09-11",
    nights: 1,
    rooms: 2,
    min_krw: 250_000,
    max_krw: 450_000,
    status: "공항접근추천",
    alternative: "Wakeup Copenhagen Bernstorffsgade",
    url: "https://en.cabinn.com/hotel/cabinn-metro",
    notes:
      "최근 공개 평균 약 DKK879/실·박. Ørestad역·CPH 공항 접근성 우선.",
    sort_order: 50,
  },
];

const meetings = [
  {
    id: "m1",
    day_id: 1,
    organization: "TIPC · Port of Taichung",
    agenda: "대만 해상풍력 O&M 항만 운영·개발계획",
    recommended_duration: "1시간 50분",
    contact: "",
    status: "일정협의 필요",
    photo_allowed: false,
    ppe_required: false,
    interpreter_needed: true,
    url: "https://tc.twport.com.tw/en",
    notes: "No.2, Sec.10, Taiwan Blvd., Wuqi",
    sort_order: 10,
  },
  {
    id: "m2",
    day_id: 2,
    organization: "VESTAS O&M Base",
    agenda: "터빈 O&M 기술·정비체계·예비품·TIPC 공동 결과공유",
    recommended_duration: "5시간",
    contact: "",
    status: "일정협의 필요",
    photo_allowed: true,
    ppe_required: true,
    interpreter_needed: true,
    url: "https://www.google.com/maps/search/?api=1&query=24.0765986,120.3773545",
    notes: "No.45, Lugong Rd., Lukang",
    sort_order: 20,
  },
  {
    id: "m3",
    day_id: 6,
    organization: "Port of Rotterdam Authority",
    agenda: "해상풍력 O&M 항만 추진·운영계획",
    recommended_duration: "2시간 10분",
    contact: "",
    status: "일정협의 필요",
    photo_allowed: false,
    ppe_required: false,
    interpreter_needed: false,
    url: "https://www.portofrotterdam.com/en",
    notes: "World Port Center, Wilhelminakade 909",
    sort_order: 30,
  },
  {
    id: "m4",
    day_id: 6,
    organization: "Rotterdam Offshore Group",
    agenda: "선박·풍력설비 수리·정비 작업 수행체계",
    recommended_duration: "1시간 45분",
    contact: "",
    status: "일정협의 필요",
    photo_allowed: true,
    ppe_required: true,
    interpreter_needed: false,
    url: "https://www.rotterdamoffshore.com/",
    notes: "Drutenstraat 7, Port no. 2226",
    sort_order: 40,
  },
  {
    id: "m5",
    day_id: 6,
    organization: "TNO Rijswijk · Kesslerpark",
    agenda: "해상풍력 O&M 로봇점검·자동화 기술",
    recommended_duration: "90분",
    contact: "",
    status: "일정협의 필요",
    photo_allowed: false,
    ppe_required: false,
    interpreter_needed: false,
    url: "https://www.tno.nl/en/about-tno/contact/locations/rijswijk-kesslerpark/",
    notes: "Kesslerpark 1, 2288 GS Rijswijk",
    sort_order: 50,
  },
  {
    id: "m8",
    day_id: 8,
    organization: "DNV Hamburg",
    agenda: "유럽 해상풍력 기술동향·Digital Twin의 설계/건설/운영 적용·운영데이터/상태모니터링/O&M 최적화·프로젝트 인증 및 기술검증·기술리스크 대응",
    recommended_duration: "90분",
    contact: "",
    status: "9/9 08:30 권고안·회신 대기",
    photo_allowed: false,
    ppe_required: false,
    interpreter_needed: false,
    url: "https://www.dnv.com/contact/digital-solutions/",
    notes: "Brooktorkai 18, 20457 Hamburg · OWC 9/8 10:00 요청에 따라 9/9 08:30~09:40으로 재배치 권고. 10:53 ECE396 탑승 연계.",
    sort_order: 55,
  },
  {
    id: "m6",
    day_id: 7,
    organization: "Skyborn Renewables Hamburg",
    agenda: "유럽 해상풍력 사업개발 선진사례·주요 추진사례·개발 및 추진과정 주요 이슈와 대응 경험·국내 사업 적용 시사점",
    recommended_duration: "90분",
    contact: "",
    status: "요청 중",
    photo_allowed: false,
    ppe_required: false,
    interpreter_needed: false,
    url: "https://www.skybornrenewables.com/contact",
    notes: "Ericusspitze 2-4, 20457 Hamburg · 희망 9/8 오후 또는 9/9 오전",
    sort_order: 60,
  },
  {
    id: "m9",
    day_id: 7,
    organization: "OWC Germany · Hamburg",
    agenda: "독일 해상풍력 Independent Engineering·기술실사·Lender’s Technical Advisory·Owner’s Engineering·Technical Risk·주요 패키지 기술검토·설계 최적화 및 LCoE 절감",
    recommended_duration: "90분 계획",
    contact: "Christian Apeah · Global Head of Independent Engineering / 기술실사·Lender’s Technical Advisory 부문장",
    status: "Christian Apeah 참석 확정·9/8 10:00 요청·장소 조율 중",
    photo_allowed: false,
    ppe_required: false,
    interpreter_needed: false,
    url: "https://owcltd.com/our-people/",
    notes: "Christian Apeah 참석 확정. 9/8 오전 10시를 최신 요청시간으로 반영. 해당 주간 OWC Hamburg 사무실 이전으로 장소는 조율 중이며 회신 즉시 지도와 이동시간 재계산.",
    sort_order: 65,
  },
  {
    id: "m7",
    day_id: 9,
    organization: "Blue Water Shipping · Esbjerg",
    agenda: "해상풍력 터빈 공급망·운송·보관·통관",
    recommended_duration: "2시간",
    contact: "",
    status: "일정협의 필요",
    photo_allowed: false,
    ppe_required: false,
    interpreter_needed: false,
    url: "https://www.bws.net/contact/denmark/esbjerg",
    notes: "Trafikhavnskaj 9, 6700 Esbjerg",
    sort_order: 70,
  },
  {
    id: "m10",
    day_id: 9,
    organization: "OWC Denmark · Aarhus",
    agenda: "덴마크·북해 Owner’s Engineering/Technical Advisory·Technical Risk·주요 패키지 기술검토·Engineering 최적화·Asset Management·BoP O&M·WTG 설치·운영·최적화·독일 대비 덴마크 시장 차이",
    recommended_duration: "15:00 시작 확정·90분 계획",
    contact: "René Aagaard · Country Manager / Rune Nørgaard · Deputy Country Manager",
    status: "9/10 15:00·주소·참석자 확정",
    photo_allowed: false,
    ppe_required: false,
    interpreter_needed: false,
    url: "https://owcltd.com/offices/aarhus-2/",
    notes: "Banegårdspladsen 4, 2. sal th, 8000 Aarhus C. Esbjerg에서 차량 최대 약 2시간 안내. 종료시각은 미확정이므로 출장 동선상 16:30을 계획값으로 설정.",
    sort_order: 80,
  },
];

const transportOptions = [
  {
    id: "t1",
    region: "대만",
    recommendation: "택시/기사차량 + THSR",
    reason: "4인 분산 이동은 택시가 대중교통 4인 합계와 유사하고 업무지 접근이 빠름",
    min_krw: 600_000,
    max_krw: 950_000,
    notes: "타이중항·루강 차량, 타이중→타오위안 THSR 포함",
    sort_order: 10,
  },
  {
    id: "t2",
    region: "네덜란드",
    recommendation: "NS 열차 + 업무일 택시",
    reason: "도심 주차비·렌터카 반납시간 제거",
    min_krw: 450_000,
    max_krw: 750_000,
    notes: "AMS→Rotterdam, Port Authority→ROG→TNO 택시",
    sort_order: 20,
  },
  {
    id: "t3",
    region: "로테르담→함부르크",
    recommendation: "NS/DB 국제열차",
    reason: "항공보다 4인 약 100만원 이상 절약 가능·도심 간 이동",
    min_krw: 210_000,
    max_krw: 500_000,
    notes: "네덜란드발 조기운임 €33부터·로테르담 기준 약 6시간 4분",
    sort_order: 30,
  },
  {
    id: "t4",
    region: "함부르크→에스비에르",
    recommendation: "DB/DSB 열차",
    reason: "4인 렌터카 국경 편도반납료 회피",
    min_krw: 220_000,
    max_krw: 450_000,
    notes: "조기운임 US$35/€30대부터·빠른 Kolding 연결편 선택",
    sort_order: 40,
  },
  {
    id: "t5",
    region: "에스비에르→오르후스→코펜하겐",
    recommendation: "전용차량/대형택시 + DSB InterCityLyn",
    reason: "9/10 15:00 OWC Denmark Aarhus 미팅 확정으로 Esbjerg→Aarhus 차량 이동 후 역전 사무실에서 바로 Aarhus H 철도 연계",
    min_krw: 620_000,
    max_krw: 1_200_000,
    notes: "Esbjerg→Aarhus 차량 견적 별도 확인 · Aarhus H→København H Orange 운임 우선 · 9/10 선로공사 3일 전 재확인",
    sort_order: 50,
  },
];

const restaurants = [
  {
    id: "r1",
    day_id: 1,
    name: "Wuqi Fishing Harbor",
    city: "Taichung Port",
    meal_type: "간식·이른 저녁",
    price_per_person: "TWD 300~700",
    url: "https://www.google.com/maps/search/?api=1&query=Wuqi+Fishing+Harbor",
    notes: "TIPC에서 가까운 해산물시장",
    sort_order: 10,
  },
  {
    id: "r2",
    day_id: 2,
    name: "Chun Shui Tang Siwei Original Store",
    city: "Taichung",
    meal_type: "저녁",
    price_per_person: "TWD 350~700",
    url: "https://www.chunshuitang.com.tw/",
    notes: "버블티 원조점·예약 또는 대기시간 확인",
    sort_order: 20,
  },
  {
    id: "r3",
    day_id: 4,
    name: "Markthal Rotterdam",
    city: "Rotterdam",
    meal_type: "점심",
    price_per_person: "EUR 12~25",
    url: "https://www.markthal.nl/en/",
    notes: "선택지가 많고 관광 동선과 결합",
    sort_order: 30,
  },
  {
    id: "r4",
    day_id: 4,
    name: "Restaurant Bazar",
    city: "Rotterdam",
    meal_type: "저녁",
    price_per_person: "EUR 20~35",
    url: "https://hotelbazar.nl/en/restaurant-bazar/",
    notes: "중동·북아프리카 요리·도심 중가",
    sort_order: 40,
  },
  {
    id: "r5",
    day_id: 7,
    name: "Oberhafen-Kantine",
    city: "Hamburg",
    meal_type: "점심",
    price_per_person: "EUR 18~30",
    url: "https://www.google.com/maps/search/?api=1&query=Oberhafen-Kantine+Hamburg",
    notes: "Skyborn·Speicherstadt 동선",
    sort_order: 50,
  },
  {
    id: "r6",
    day_id: 8,
    name: "Esbjerg Street Food",
    city: "Esbjerg",
    meal_type: "저녁",
    price_per_person: "DKK 100~180",
    url: "https://www.google.com/maps/search/?api=1&query=Esbjerg+Street+Food",
    notes: "Hotel Britannia 레스토랑보다 저렴한 선택",
    sort_order: 60,
  },
  {
    id: "r7",
    day_id: 9,
    name: "Field's Food Court",
    city: "Copenhagen",
    meal_type: "저녁",
    price_per_person: "DKK 100~180",
    url: "https://fields.steenstrom.dk/",
    notes: "CABINN Metro 도보권",
    sort_order: 70,
  },
];

function buildMapPoints(mode) {
  const saving = mode === "cost_optimized";
  const day3 = [
        {
          id: "p14",
          day_id: 3,
          name: "CHECK Inn Taichung LaiLai · Sanmin Rd. 125",
          lat: 24.1406,
          lng: 120.6841,
          sort_order: 1,
          segment_type: "car",
          popup: "출발",
          url: "",
        },
        {
          id: "p15",
          day_id: 3,
          name: "National Taichung Theater",
          lat: 24.1629,
          lng: 120.6404,
          sort_order: 2,
          segment_type: "car",
          popup: "관광",
          url: "https://www.npac-ntt.org/en",
        },
        {
          id: "p16",
          day_id: 3,
          name: "THSR Taichung",
          lat: 24.1127,
          lng: 120.616,
          sort_order: 3,
          segment_type: "car",
          popup: "고속철도 환승",
          url: "https://en.thsrc.com.tw/",
        },
        {
          id: "p17",
          day_id: 3,
          name: "THSR Taoyuan",
          lat: 25.0138,
          lng: 121.2147,
          sort_order: 4,
          segment_type: "hsr",
          popup: "Airport MRT 환승",
          url: "",
        },
        {
          id: "p18",
          day_id: 3,
          name: "Taoyuan Airport",
          lat: 25.0797,
          lng: 121.2342,
          sort_order: 5,
          segment_type: "subway",
          popup: "23:10 출발",
          url: "",
        },
        {
          id: "p19",
          day_id: 3,
          name: "Schiphol Airport",
          lat: 52.3105,
          lng: 4.7683,
          sort_order: 6,
          segment_type: "flight",
          popup: "9/5 07:40 도착",
          url: "",
        },
      ];

  return [
    {
      id: "p01",
      day_id: 1,
      name: "인천공항",
      lat: 37.4587,
      lng: 126.442,
      sort_order: 1,
      segment_type: "flight",
      popup: "07:55 출발",
      url: "",
    },
    {
      id: "p02",
      day_id: 1,
      name: "Taichung Airport",
      lat: 24.2647,
      lng: 120.6208,
      sort_order: 2,
      segment_type: "flight",
      popup: "09:40 도착",
      url: "",
    },
    {
      id: "p03",
      day_id: 1,
      name: "CHECK Inn Taichung LaiLai · Sanmin Rd. 125",
      lat: 24.147736,
      lng: 120.673645,
      sort_order: 3,
      segment_type: "car",
      popup: "도착 후 짐 보관 · 체크인 16:00 이후",
      url: "https://www.checkinn.com.tw/?page_id=22115",
    },
    {
      id: "p04",
      day_id: 1,
      name: "TIPC · Port of Taichung",
      lat: 24.256,
      lng: 120.521,
      sort_order: 4,
      segment_type: "car",
      popup: "14:10 회의",
      url: "https://tc.twport.com.tw/en",
    },
    {
      id: "p05",
      day_id: 1,
      name: "Wuqi Fishing Harbor",
      lat: 24.2926,
      lng: 120.5212,
      sort_order: 5,
      segment_type: "car",
      popup: "해산물시장",
      url: "",
    },
    {
      id: "p06",
      day_id: 1,
      name: "Gaomei Wetlands",
      lat: 24.3124,
      lng: 120.5496,
      sort_order: 6,
      segment_type: "car",
      popup: "일몰",
      url: "",
    },
    {
      id: "p07",
      day_id: 1,
      name: "CHECK Inn Taichung LaiLai · Sanmin Rd. 125",
      lat: 24.147736,
      lng: 120.673645,
      sort_order: 7,
      segment_type: "car",
      popup: "예약숙박 · 16:00 이후 체크인",
      url: "",
    },
    {
      id: "p08",
      day_id: 2,
      name: "CHECK Inn Taichung LaiLai · Sanmin Rd. 125",
      lat: 24.147736,
      lng: 120.673645,
      sort_order: 1,
      segment_type: "car",
      popup: "08:40 출발",
      url: "",
    },
    {
      id: "p09",
      day_id: 2,
      name: "VESTAS O&M Base",
      lat: 24.0766,
      lng: 120.3774,
      sort_order: 2,
      segment_type: "car",
      popup: "10:30 회의",
      url: "",
    },
    {
      id: "p10",
      day_id: 2,
      name: "Lukang Old Street",
      lat: 24.056,
      lng: 120.435,
      sort_order: 3,
      segment_type: "car",
      popup: "관광",
      url: "",
    },
    {
      id: "p11",
      day_id: 2,
      name: "CHECK Inn Taichung LaiLai · Sanmin Rd. 125",
      lat: 24.147736,
      lng: 120.673645,
      sort_order: 4,
      segment_type: "car",
      popup: "숙박",
      url: "",
    },
    ...day3,
    {
      id: "p20",
      day_id: 4,
      name: "Schiphol Airport",
      lat: 52.3105,
      lng: 4.7683,
      sort_order: 1,
      segment_type: "rail",
      popup: "07:40 도착",
      url: "",
    },
    {
      id: "p21",
      day_id: 4,
      name: "Rotterdam Centraal",
      lat: 51.9244,
      lng: 4.4699,
      sort_order: 2,
      segment_type: "rail",
      popup: "NS Intercity",
      url: "",
    },
    {
      id: "p22",
      day_id: 4,
      name: "PREMIER SUITES Rotterdam · Weena 710",
      lat: 51.9225689,
      lng: 4.469973,
      sort_order: 3,
      segment_type: "subway",
      popup: "짐 보관·숙박",
      url: "https://www.premiersuiteseurope.com/en/locations/the-netherlands/rotterdam/serviced-apartments-rotterdam",
    },
    {
      id: "p23",
      day_id: 4,
      name: "Markthal Rotterdam",
      lat: 51.9201,
      lng: 4.4869,
      sort_order: 4,
      segment_type: "subway",
      popup: "관광·점심",
      url: "https://www.markthal.nl/en/",
    },
    {
      id: "p24",
      day_id: 4,
      name: "Historic Delfshaven",
      lat: 51.9087,
      lng: 4.4481,
      sort_order: 5,
      segment_type: "subway",
      popup: "관광",
      url: "",
    },
    {
      id: "p25",
      day_id: 4,
      name: "Restaurant Bazar",
      lat: 51.916,
      lng: 4.477,
      sort_order: 6,
      segment_type: "subway",
      popup: "저녁",
      url: "https://hotelbazar.nl/en/restaurant-bazar/",
    },
    {
      id: "p26",
      day_id: 5,
      name: "PREMIER SUITES Rotterdam · Weena 710",
      lat: 51.9225689,
      lng: 4.469973,
      sort_order: 1,
      segment_type: "subway",
      popup: "출발",
      url: "",
    },
    {
      id: "p27",
      day_id: 5,
      name: "Erasmusbrug Waterbus",
      lat: 51.909,
      lng: 4.486,
      sort_order: 2,
      segment_type: "subway",
      popup: "Waterbus",
      url: "https://www.waterbus.nl/en/",
    },
    {
      id: "p28",
      day_id: 5,
      name: "Kinderdijk",
      lat: 51.882,
      lng: 4.6331,
      sort_order: 3,
      segment_type: "subway",
      popup: "풍차군",
      url: "https://kinderdijk.com/",
    },
    {
      id: "p29",
      day_id: 5,
      name: "Fenix Food Factory",
      lat: 51.9045,
      lng: 4.485,
      sort_order: 4,
      segment_type: "subway",
      popup: "저녁",
      url: "",
    },
    {
      id: "p30",
      day_id: 6,
      name: "PREMIER SUITES Rotterdam · Weena 710",
      lat: 51.9225689,
      lng: 4.469973,
      sort_order: 1,
      segment_type: "car",
      popup: "08:50 출발",
      url: "",
    },
    {
      id: "p31",
      day_id: 6,
      name: "Port of Rotterdam Authority",
      lat: 51.9044,
      lng: 4.4841,
      sort_order: 2,
      segment_type: "car",
      popup: "09:20 회의",
      url: "https://www.portofrotterdam.com/en",
    },
    {
      id: "p32",
      day_id: 6,
      name: "Rotterdam Offshore Group",
      lat: 51.8788,
      lng: 4.445,
      sort_order: 3,
      segment_type: "car",
      popup: "12:25 현장견학",
      url: "https://www.rotterdamoffshore.com/",
    },
    {
      id: "p33",
      day_id: 6,
      name: "TNO Kesslerpark",
      lat: 52.036,
      lng: 4.325,
      sort_order: 4,
      segment_type: "car",
      popup: "15:00 회의",
      url: "https://www.tno.nl/en/about-tno/contact/locations/rijswijk-kesslerpark/",
    },
    {
      id: "p33a",
      day_id: 6,
      name: "PREMIER SUITES Rotterdam · Weena 710 · 짐 회수",
      lat: 51.9225689,
      lng: 4.469973,
      sort_order: 5,
      segment_type: "car",
      popup: "TNO 미팅 후 수하물 회수",
      url: "https://www.premiersuiteseurope.com/en/locations/the-netherlands/rotterdam/serviced-apartments-rotterdam",
    },
    {
      id: "p34",
      day_id: 6,
      name: "Rotterdam Centraal",
      lat: 51.9244,
      lng: 4.4699,
      sort_order: 6,
      segment_type: "car",
      popup: "국제열차",
      url: "",
    },
    {
      id: "p35",
      day_id: 6,
      name: "Hamburg Hbf",
      lat: 53.5527,
      lng: 10.0067,
      sort_order: 6,
      segment_type: "rail",
      popup: "23:16 후보 도착",
      url: "",
    },
    {
      id: "p36",
      day_id: 6,
      name: "Best Western Plus Hotel St. Raphael · Adenauerallee 41",
      lat: 53.55293,
      lng: 10.01636,
      sort_order: 7,
      segment_type: "walk",
      popup: "숙박",
      url: "https://www.booking.com/hotel/de/straphaelbestwesternhh.html",
    },
    {
      id: "p37", day_id: 7, name: "Best Western Plus Hotel St. Raphael · Adenauerallee 41", lat: 53.55293, lng: 10.01636, sort_order: 1, segment_type: "walk", popup: "07:30 조식·OWC 준비", url: "https://www.booking.com/hotel/de/straphaelbestwesternhh.html",
    },
    {
      id: "p38", day_id: 7, name: "OWC Hamburg · 실제 장소 확정 대기", lat: 53.5506, lng: 9.9920, sort_order: 2, segment_type: "car", popup: "9/8 10:00 요청 · Christian Apeah 참석 확정 · 이 핀은 도심 임시표시", url: "https://owcltd.com/our-people/",
    },
    {
      id: "p39", day_id: 7, name: "Skyborn Renewables · Ericusspitze 2-4", lat: 53.5454, lng: 10.0032, sort_order: 3, segment_type: "walk", popup: "13:00 사업개발 미팅 요청", url: "https://www.skybornrenewables.com/contact",
    },
    {
      id: "p40", day_id: 7, name: "Best Western Plus Hotel St. Raphael", lat: 53.55293, lng: 10.01636, sort_order: 4, segment_type: "subway", popup: "15:00 회의내용 정리", url: "https://www.booking.com/hotel/de/straphaelbestwesternhh.html",
    },
    {
      id: "p40a", day_id: 7, name: "Elbphilharmonie", lat: 53.5413, lng: 9.9841, sort_order: 5, segment_type: "subway", popup: "16:30 이후", url: "https://www.elbphilharmonie.de/en/plaza-tickets",
    },
    {
      id: "p40b", day_id: 7, name: "Landungsbrücken", lat: 53.5461, lng: 9.9663, sort_order: 6, segment_type: "subway", popup: "저녁", url: "",
    },
    {
      id: "p41", day_id: 8, name: "Best Western Plus Hotel St. Raphael · Adenauerallee 41", lat: 53.55293, lng: 10.01636, sort_order: 1, segment_type: "car", popup: "07:15 조식·체크아웃·짐보관", url: "https://www.booking.com/hotel/de/straphaelbestwesternhh.html",
    },
    {
      id: "p41a", day_id: 8, name: "DNV Hamburg · Brooktorkai 18", lat: 53.5430, lng: 10.0030, sort_order: 2, segment_type: "car", popup: "08:30~09:40 미팅 권고안", url: "https://www.dnv.com/contact/digital-solutions/",
    },
    {
      id: "p41b", day_id: 8, name: "Best Western Plus Hotel St. Raphael · 짐 회수", lat: 53.55293, lng: 10.01636, sort_order: 3, segment_type: "car", popup: "09:55 전후 짐 회수", url: "https://www.booking.com/hotel/de/straphaelbestwesternhh.html",
    },
    {
      id: "p42", day_id: 8, name: "Hamburg Hbf", lat: 53.5527, lng: 10.0067, sort_order: 4, segment_type: "walk", popup: "10:53 ECE 396 출발", url: "",
    },
    {
      id: "p42a", day_id: 8, name: "Kolding St.", lat: 55.4904, lng: 9.4723, sort_order: 5, segment_type: "rail", popup: "13:44 도착 · 14:06 IC2340 환승", url: "",
    },
    {
      id: "p43", day_id: 8, name: "Esbjerg Station", lat: 55.4667, lng: 8.4578, sort_order: 6, segment_type: "rail", popup: "14:54 도착", url: "",
    },
    {
      id: "p44", day_id: 8, name: "CABINN Plus Esbjerg", lat: 55.4676, lng: 8.4525, sort_order: 7, segment_type: "walk", popup: "15:30 체크인", url: "https://en.cabinn.com/hotel/cabinn-esbjerg-plus",
    },
    {
      id: "p45", day_id: 8, name: "Men at Sea", lat: 55.4870, lng: 8.4108, sort_order: 8, segment_type: "subway", popup: "15:45 이후", url: "",
    },
    {
      id: "p46", day_id: 9, name: "CABINN Plus Esbjerg", lat: 55.4676, lng: 8.4525, sort_order: 1, segment_type: "car", popup: "09:05 짐 동반 출발", url: "",
    },
    {
      id: "p47", day_id: 9, name: "Blue Water Shipping · Trafikhavnskaj 9", lat: 55.4650, lng: 8.4430, sort_order: 2, segment_type: "car", popup: "09:30~11:30 회의", url: "https://www.bws.net/contact/denmark/esbjerg",
    },
    {
      id: "p47a", day_id: 9, name: "Kolding · E20/E45", lat: 55.4904, lng: 9.4723, sort_order: 3, segment_type: "car", popup: "Aarhus 차량 이동 경유축", url: "",
    },
    {
      id: "p47b", day_id: 9, name: "Vejle · E45", lat: 55.7113, lng: 9.5364, sort_order: 4, segment_type: "car", popup: "Aarhus 차량 이동 경유축", url: "",
    },
    {
      id: "p47c", day_id: 9, name: "Horsens · E45", lat: 55.8607, lng: 9.8503, sort_order: 5, segment_type: "car", popup: "Aarhus 차량 이동 경유축", url: "",
    },
    {
      id: "p48", day_id: 9, name: "OWC Denmark · Banegårdspladsen 4", lat: 56.1503, lng: 10.2039, sort_order: 6, segment_type: "car", popup: "15:00 미팅 확정 · René Aagaard / Rune Nørgaard", url: "https://owcltd.com/offices/aarhus-2/",
    },
    {
      id: "p48a", day_id: 9, name: "Aarhus H", lat: 56.1500, lng: 10.2030, sort_order: 7, segment_type: "walk", popup: "17:20 ICL 50058 후보", url: "https://www.dsb.dk/en/",
    },
    {
      id: "p48b", day_id: 9, name: "Skanderborg St.", lat: 56.0340, lng: 9.9270, sort_order: 8, segment_type: "rail", popup: "열차 경유", url: "",
    },
    {
      id: "p48c", day_id: 9, name: "Horsens St.", lat: 55.8610, lng: 9.8450, sort_order: 9, segment_type: "rail", popup: "열차 경유", url: "",
    },
    {
      id: "p48d", day_id: 9, name: "Vejle St.", lat: 55.7068, lng: 9.5364, sort_order: 10, segment_type: "rail", popup: "열차 경유", url: "",
    },
    {
      id: "p48e", day_id: 9, name: "Fredericia St.", lat: 55.5683, lng: 9.7538, sort_order: 11, segment_type: "rail", popup: "열차 경유", url: "",
    },
    {
      id: "p48f", day_id: 9, name: "Odense St.", lat: 55.4012, lng: 10.3873, sort_order: 12, segment_type: "rail", popup: "열차 경유", url: "",
    },
    {
      id: "p48g", day_id: 9, name: "Ringsted St.", lat: 55.4425, lng: 11.7901, sort_order: 13, segment_type: "rail", popup: "열차 경유", url: "",
    },
    {
      id: "p49", day_id: 9, name: "København H", lat: 55.6727, lng: 12.5646, sort_order: 14, segment_type: "rail", popup: "20:36 도착 후보", url: "",
    },
    {
      id: "p49a", day_id: 9, name: "Ørestad St.", lat: 55.6280, lng: 12.5790, sort_order: 15, segment_type: "subway", popup: "호텔 환승", url: "",
    },
    {
      id: "p50", day_id: 9, name: "CABINN Metro", lat: 55.6307, lng: 12.5778, sort_order: 16, segment_type: "walk", popup: "체크인·숙박", url: "https://en.cabinn.com/hotel/cabinn-metro",
    },
    {
      id: "p51",
      day_id: 10,
      name: "CABINN Metro",
      lat: 55.6307,
      lng: 12.5778,
      sort_order: 1,
      segment_type: "subway",
      popup: "06:45 출발",
      url: "",
    },
    {
      id: "p52",
      day_id: 10,
      name: "Copenhagen Airport",
      lat: 55.6181,
      lng: 12.656,
      sort_order: 2,
      segment_type: "subway",
      popup: "10:25 출발",
      url: "",
    },
    {
      id: "p53",
      day_id: 10,
      name: "Istanbul Airport",
      lat: 41.2753,
      lng: 28.7519,
      sort_order: 3,
      segment_type: "flight",
      popup: "2시간 15분 환승",
      url: "",
    },
    {
      id: "p54",
      day_id: 10,
      name: "인천공항",
      lat: 37.4587,
      lng: 126.442,
      sort_order: 4,
      segment_type: "flight",
      popup: "9/12 08:35 도착",
      url: "",
    },
    {
      id: "p55",
      day_id: 11,
      name: "인천공항",
      lat: 37.4587,
      lng: 126.442,
      sort_order: 1,
      segment_type: "flight",
      popup: "08:35 도착·입국",
      url: "",
    },
  ];
}

function buildBudget(mode) {
  return [
    {
      id: "b1",
      category: "항공",
      label: "3개 장거리·국제 항공 구간·4인 자동조회",
      min_krw: 0,
      max_krw: 0,
      notes: "선택 일정의 Google Flights 채택가 합계로 자동 대체",
      sort_order: 10,
    },
    {
      id: "b2",
      category: "숙박",
      label: "호텔 8박·기본 2실(함부르크 3실 예약)",
      min_krw: 2_100_000,
      max_krw: 3_450_000,
      notes:
        "Taichung 2박, Rotterdam 2박, Hamburg 2박(객실 3개 예약), Esbjerg 1박, Copenhagen 1박",
      sort_order: 20,
    },
    {
      id: "b3",
      category: "교통",
      label: "택시·기사차량·THSR·유럽철도·대중교통",
      min_krw: 2_100_000,
      max_krw: 3_400_000,
      notes: "4인 기준·국경 편도 렌터카 미사용",
      sort_order: 30,
    },
    {
      id: "b4",
      category: "식비·관광",
      label: "식사·입장권·Waterbus",
      min_krw: 3_000_000,
      max_krw: 4_800_000,
      notes: "무료 외부 관광 중심·유료 박물관은 선택",
      sort_order: 40,
    },
    {
      id: "b5",
      category: "기타",
      label: "보험·PPE·통역·수하물·좌석료",
      min_krw: 1_000_000,
      max_krw: 1_800_000,
      notes:
        "항공 연결발권·직항 모두 수하물·좌석료 최종 예약화면 확인",
      sort_order: 50,
    },
  ];
}

function buildSeed(mode) {
  return {
    days: buildDays(mode),
    events: buildEvents(mode),
    flights: buildFlights(mode),
    hotels,
    meetings,
    transport_options: transportOptions,
    restaurants,
    map_points: buildMapPoints(mode),
    budget_items: buildBudget(mode),
  };
}

export const ITINERARIES = {
  cost_optimized: {
    meta: planMeta.cost_optimized,
    officialSeed: buildSeed("cost_optimized"),
  },
  time_optimized: {
    meta: planMeta.time_optimized,
    officialSeed: buildSeed("time_optimized"),
  },
};
