export const APP_VERSION = "PDF_ROUTE_COST_OPTIMIZED_V2";
export const DEFAULT_ITINERARY = "cost_optimized";

const SOURCE_PLAN = "260729_공무 국외출장 계획서(초안)";
const PDF_AIRFARE_BASELINE = 14_495_252;

const e = (
  id,
  day_id,
  time_start,
  time_end,
  title,
  category,
  location,
  transport,
  duration,
  extras = {},
) => ({
  id,
  day_id,
  time_start,
  time_end,
  title,
  category,
  location,
  transport,
  duration,
  original_currency: null,
  original_min: null,
  original_max: null,
  min_cost_krw: null,
  max_cost_krw: null,
  cost_basis: null,
  booking_url: null,
  official_url: null,
  map_url: null,
  notes: null,
  sort_order: (Number(String(id).split("-").pop()) || 0) * 10,
  updated_at: new Date().toISOString(),
  ...extras,
});

const sharedMeta = {
  title: "공무 국외출장 일정·비용 대시보드 2026",
  dates: "2026.09.02–09.12",
  route:
    "인천 → 타이중·루강 → 타오위안 → 암스테르담·로테르담·라이스베이크 → 함부르크 → 에스비에르 → 코펜하겐 → 인천",
  travelers: 4,
  hotelNights: 8,
  flightNights: 2,
  noHotelStopovers: 2,
  durationText: "9박 11일",
  lodgingNote: "호텔 8박·기내 2박",
  budgetNote:
    "성인 4명·일반석. 항공은 Google Flights 자동조회, 숙박은 4인·2실 검색 링크, 10% 예비비 포함",
  lastVerified: "2026-07-31",
  sourcePlan: SOURCE_PLAN,
  includesAwtec: false,
  flightCount: 3,
  businessLocationRule: "첨부 계획서의 업무장소 7곳만 유지",
  pdfAirfareBaseline: PDF_AIRFARE_BASELINE,
};

const planMeta = {
  cost_optimized: {
    ...sharedMeta,
    key: "cost_optimized",
    tabLabel: "추천안 · 비용 최적",
    tabNote: "광저우 환승 · 유럽 철도 · 코펜하겐 귀국",
    subtitle:
      "첨부 계획서의 도시·업무장소 순서 유지 · 장거리 항공 3구간으로 단순화 · 숙박은 업무 접근성을 지키는 저가 후보",
    taiwanWindow: "9/2 09:40–9/4 11:20",
    taiwanDuration: "약 2일 2시간",
    budgetMin: 17_800_000,
    budgetMax: 23_500_000,
    recommendation:
      "광저우 7시간 환승을 감수하고 4인 항공비를 가장 크게 줄일 때 선택",
  },
  time_optimized: {
    ...sharedMeta,
    key: "time_optimized",
    tabLabel: "비교안 · 직항 우선",
    tabNote: "TPE→AMS 직항 · 나머지는 추천안과 동일",
    subtitle:
      "첨부 계획서의 도시·업무장소 순서 유지 · 대만에서 유럽만 직항으로 이동 · 귀국은 코펜하겐 1회 환승",
    taiwanWindow: "9/2 09:40–9/4 20:00",
    taiwanDuration: "약 2일 10시간",
    budgetMin: 19_700_000,
    budgetMax: 25_400_000,
    recommendation:
      "4인 약 190만원을 더 내고 광저우 환승과 약 8시간의 추가 이동을 피할 때 선택",
  },
};

function buildDays(mode) {
  const saving = mode === "cost_optimized";
  return [
    {
      id: 1,
      date: "2026-09-02",
      weekday: "수요일",
      cities: "인천 → 타이중항 → 타이중",
      lodging: "Holiday Inn Express Taichung Park",
      summary:
        "07:55 RMQ 직항 · TIPC 회의 · 우치항·가오메이 습지 · 계획서 첫날 유지",
    },
    {
      id: 2,
      date: "2026-09-03",
      weekday: "목요일",
      cities: "타이중 → 루강 → 타이중",
      lodging: "Holiday Inn Express Taichung Park",
      summary:
        "VESTAS O&M Base 현장·회의 · TIPC 공동 결과공유 · 루강 옛거리",
    },
    {
      id: 3,
      date: "2026-09-04",
      weekday: "금요일",
      cities: saving
        ? "타이중 → 타오위안 → 광저우 → 암스테르담"
        : "타이중 → 타오위안 → 암스테르담",
      lodging: "기내박",
      summary: saving
        ? "14:50 TPE→CAN→AMS · 직항보다 4인 약 190만원 절감 · 24시간 무비자 환승 조건 확인"
        : "타이중 오전 관광 · 23:10 TPE→AMS 중화항공 직항",
    },
    {
      id: 4,
      date: "2026-09-05",
      weekday: "토요일",
      cities: "암스테르담 → 로테르담",
      lodging: "Holiday Inn Express Rotterdam Central",
      summary:
        "스키폴 직통열차 · Markthal·큐브하우스 · 13:00 네덜란드 일정 점검회의",
    },
    {
      id: 5,
      date: "2026-09-06",
      weekday: "일요일",
      cities: "로테르담·킨더다이크",
      lodging: "Holiday Inn Express Rotterdam Central",
      summary:
        "오전 향후 일정 점검 · 오후 Waterbus로 킨더다이크 · 무료 외부 동선 중심",
    },
    {
      id: 6,
      date: "2026-09-07",
      weekday: "월요일",
      cities: "로테르담·라이스베이크 → 함부르크",
      lodging: "Motel One Hamburg-Fleetinsel",
      summary:
        "Port of Rotterdam·ROG·TNO 회의 · 저녁 국제열차로 함부르크 이동",
    },
    {
      id: 7,
      date: "2026-09-08",
      weekday: "화요일",
      cities: "함부르크",
      lodging: "Motel One Hamburg-Fleetinsel",
      summary:
        "Skyborn Renewables 회의 · HafenCity·Speicherstadt·Elbphilharmonie",
    },
    {
      id: 8,
      date: "2026-09-09",
      weekday: "수요일",
      cities: "함부르크 → 에스비에르",
      lodging: "CABINN Plus Esbjerg",
      summary:
        "DB/DSB 조기열차로 환승 대기 단축 · Men at Sea·에스비에르 항만",
    },
    {
      id: 9,
      date: "2026-09-10",
      weekday: "목요일",
      cities: "에스비에르 → 코펜하겐",
      lodging: "CABINN Metro Copenhagen",
      summary:
        "Blue Water Shipping 회의·내용정리 후 DSB로 코펜하겐 이동 · EBJ/ABZ 환승 제거",
    },
    {
      id: 10,
      date: "2026-09-11",
      weekday: "금요일",
      cities: "코펜하겐 → 이스탄불 → 인천",
      lodging: "기내박",
      summary:
        "10:25 CPH 출발 · 이스탄불 1회 환승 · 계획서 EBJ→ABZ→AMS보다 짧고 저렴",
    },
    {
      id: 11,
      date: "2026-09-12",
      weekday: "토요일",
      cities: "인천",
      lodging: "귀가",
      summary: "08:35 인천 도착·입국",
    },
  ];
}

function buildEvents(mode) {
  const saving = mode === "cost_optimized";
  const europeDeparture = saving
    ? [
        e(
          "d3-01",
          3,
          "08:00",
          "09:00",
          "조식·체크아웃",
          "숙박",
          "Holiday Inn Express Taichung Park",
          "도보",
          "60분",
        ),
        e(
          "d3-02",
          3,
          "09:00",
          "11:20",
          "타이중 → 타오위안공항",
          "교통",
          "Taichung → THSR Taoyuan → TPE",
          "택시+THSR+Airport MRT",
          "2시간 20분",
          {
            booking_url: "https://en.thsrc.com.tw/",
            min_cost_krw: 110_000,
            max_cost_krw: 180_000,
            cost_basis: "4인",
          },
        ),
        e(
          "d3-03",
          3,
          "11:20",
          "14:00",
          "출국수속·점심",
          "출국",
          "Taoyuan International Airport T2",
          "도보",
          "2시간 40분",
        ),
        e(
          "d3-04",
          3,
          "14:50",
          "17:15",
          "TPE → CAN",
          "항공",
          "Taipei → Guangzhou",
          "China Southern",
          "2시간 25분",
          {
            booking_url: "https://www.google.com/travel/flights",
            notes:
              "TPE→CAN→AMS 한 장 발권·수하물 AMS 연결 여부를 결제 전 확인.",
          },
        ),
        e(
          "d3-05",
          3,
          "17:15",
          "9/5 00:20",
          "광저우 환승",
          "환승",
          "Guangzhou Baiyun International Airport",
          "공항 내 이동",
          "7시간 5분",
          {
            official_url:
              "https://en.nia.gov.cn/n147418/n147463/c156086/content.html",
            notes:
              "대한민국 일반여권·확정된 제3국 항공권 기준 24시간 무비자 환승. 발권·수하물 연결 조건은 항공사 재확인.",
          },
        ),
        e(
          "d3-06",
          3,
          "00:20",
          "06:35",
          "CAN → AMS",
          "항공",
          "Guangzhou → Amsterdam",
          "China Southern",
          "12시간 15분",
          {
            booking_url: "https://www.google.com/travel/flights",
            notes: "Google Flights 4인 일정 채택가 자동조회.",
          },
        ),
      ]
    : [
        e(
          "d3-01",
          3,
          "08:30",
          "10:00",
          "National Taichung Theater·Calligraphy Greenway",
          "관광",
          "Taichung",
          "택시+도보",
          "90분",
          {
            official_url: "https://www.npac-ntt.org/en",
            map_url:
              "https://www.google.com/maps/search/?api=1&query=National+Taichung+Theater",
          },
        ),
        e(
          "d3-02",
          3,
          "10:20",
          "12:00",
          "Miyahara·타이중 구도심·점심",
          "관광·식사",
          "Taichung Station",
          "택시+도보",
          "1시간 40분",
          {
            map_url:
              "https://www.google.com/maps/search/?api=1&query=Miyahara+Taichung",
          },
        ),
        e(
          "d3-03",
          3,
          "13:00",
          "15:20",
          "타이중 → 타오위안공항",
          "교통",
          "Taichung → THSR Taoyuan → TPE",
          "택시+THSR+Airport MRT",
          "2시간 20분",
          {
            booking_url: "https://en.thsrc.com.tw/",
            min_cost_krw: 110_000,
            max_cost_krw: 180_000,
            cost_basis: "4인",
          },
        ),
        e(
          "d3-04",
          3,
          "15:20",
          "20:00",
          "공항 라운지·출국수속·저녁",
          "출국",
          "Taoyuan International Airport T1",
          "도보",
          "4시간 40분",
        ),
        e(
          "d3-05",
          3,
          "23:10",
          "9/5 07:40",
          "TPE → AMS 직항",
          "항공",
          "Taipei → Amsterdam",
          "China Airlines",
          "14시간 30분",
          {
            booking_url: "https://www.google.com/travel/flights",
            notes:
              "비용 최적안보다 4인 약 190만원 높지만 환승과 약 8시간의 추가 이동을 제거.",
          },
        ),
      ];

  return [
    e(
      "d1-01",
      1,
      "05:00",
      "07:00",
      "인천공항 집결·출국수속",
      "출국",
      "Incheon International Airport",
      "개별 이동",
      "2시간",
    ),
    e(
      "d1-02",
      1,
      "07:55",
      "09:40",
      "ICN → RMQ 직항",
      "항공",
      "Incheon → Taichung",
      "Jin Air",
      "2시간 45분",
      {
        booking_url: "https://www.google.com/travel/flights",
        notes: "계획서 원안과 동일. Google Flights 4인 최저가 자동조회.",
      },
    ),
    e(
      "d1-03",
      1,
      "09:40",
      "11:30",
      "입국·호텔 이동·짐 보관",
      "입국·교통",
      "RMQ → Holiday Inn Express Taichung Park",
      "택시",
      "1시간 50분",
      {
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=Taichung+International+Airport&destination=Holiday+Inn+Express+Taichung+Park",
        min_cost_krw: 35_000,
        max_cost_krw: 55_000,
        cost_basis: "차량 1대",
      },
    ),
    e(
      "d1-04",
      1,
      "11:30",
      "12:30",
      "타이중공원 산책·간단한 점심",
      "관광·식사",
      "Taichung Park",
      "도보",
      "60분",
      {
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Taichung+Park",
      },
    ),
    e(
      "d1-05",
      1,
      "12:30",
      "13:40",
      "호텔 → TIPC 타이중항만청",
      "교통",
      "No.2, Sec.10, Taiwan Blvd., Wuqi",
      "택시/기사차량",
      "약 70분",
      {
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=Holiday+Inn+Express+Taichung+Park&destination=Port+of+Taichung+Taiwan+International+Ports+Corporation",
      },
    ),
    e(
      "d1-06",
      1,
      "14:10",
      "16:00",
      "TIPC 타이중항만청 회의",
      "업무",
      "No.2, Sec.10, Taiwan Blvd., Wuqi",
      "도보",
      "1시간 50분",
      {
        official_url: "https://tc.twport.com.tw/en",
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Port+of+Taichung+Taiwan+International+Ports+Corporation",
        notes: "대만 해상풍력 O&M 항만 운영·계획 논의.",
      },
    ),
    e(
      "d1-07",
      1,
      "16:10",
      "18:20",
      "우치어항·가오메이 습지 일몰",
      "관광·식사",
      "Wuqi Fishing Harbor → Gaomei Wetlands",
      "택시/기사차량",
      "2시간 10분",
      {
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=Port+of+Taichung&destination=Gaomei+Wetlands&waypoints=Wuqi+Fishing+Harbor",
        notes: "업무지 인접 무료 관광. 기상 악화 시 호텔 복귀.",
      },
    ),
    e(
      "d1-08",
      1,
      "18:20",
      "20:00",
      "가오메이 → 호텔·체크인",
      "교통·숙박",
      "Holiday Inn Express Taichung Park",
      "택시/기사차량",
      "약 1시간 40분",
    ),
    e(
      "d2-01",
      2,
      "08:40",
      "10:10",
      "호텔 → VESTAS O&M Base",
      "교통",
      "No.45, Lugong Rd., Lukang",
      "기사차량",
      "약 90분",
      {
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=Holiday+Inn+Express+Taichung+Park&destination=No.45+Lugong+Rd+Lukang",
      },
    ),
    e(
      "d2-02",
      2,
      "10:30",
      "13:30",
      "VESTAS O&M Base 현장견학·회의·중식",
      "업무",
      "CFXD & ZN Offshore Windfarm O&M Base",
      "도보",
      "3시간",
      {
        map_url:
          "https://www.google.com/maps/search/?api=1&query=24.0765986,120.3773545",
        notes: "터빈 O&M 기술·정비체계·예비품 운영 논의.",
      },
    ),
    e(
      "d2-03",
      2,
      "13:30",
      "15:30",
      "TIPC·VESTAS 회의결과 공유",
      "업무",
      "VESTAS O&M Base",
      "도보",
      "2시간",
      {
        notes: "해상풍력 O&M 인프라·요구조건 정리.",
      },
    ),
    e(
      "d2-04",
      2,
      "15:40",
      "17:10",
      "루강 옛거리·용산사",
      "관광",
      "Lukang Old Street",
      "기사차량+도보",
      "90분",
      {
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Lukang+Old+Street",
      },
    ),
    e(
      "d2-05",
      2,
      "17:10",
      "18:20",
      "루강 → 타이중 호텔",
      "교통",
      "Lukang → Taichung",
      "기사차량",
      "70분",
    ),
    e(
      "d2-06",
      2,
      "19:00",
      "20:30",
      "춘수이탕 저녁·버블티",
      "식사",
      "Chun Shui Tang Siwei Original Store",
      "택시",
      "90분",
      {
        official_url: "https://www.chunshuitang.com.tw/",
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Chun+Shui+Tang+Siwei+Original+Store",
      },
    ),
    ...europeDeparture,
    e(
      "d4-01",
      4,
      saving ? "06:35" : "07:40",
      saving ? "08:40" : "09:40",
      "스키폴 입국·로테르담 이동",
      "입국·교통",
      "AMS → Rotterdam Centraal",
      "NS Intercity Direct",
      "약 2시간",
      {
        booking_url: "https://www.nsinternational.com/en",
        notes: "열차 약 26분 간격. 공항 도착시간에 맞춰 현장 구매 가능.",
      },
    ),
    e(
      "d4-02",
      4,
      saving ? "08:40" : "09:40",
      saving ? "09:20" : "10:20",
      "호텔 짐 보관·조식 보충",
      "숙박",
      "Holiday Inn Express Rotterdam Central",
      "도보",
      "40분",
    ),
    e(
      "d4-03",
      4,
      saving ? "09:30" : "10:30",
      "12:30",
      "Markthal·Cube Houses·Oude Haven",
      "관광·식사",
      "Rotterdam Centrum",
      "메트로+도보",
      saving ? "3시간" : "2시간",
      {
        official_url: "https://www.markthal.nl/en/",
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=Rotterdam+Centraal&destination=Oude+Haven+Rotterdam&waypoints=Markthal+Rotterdam%7CCube+Houses",
        notes: "외부·시장 중심 저비용 동선.",
      },
    ),
    e(
      "d4-04",
      4,
      "13:00",
      "16:00",
      "네덜란드 일정 점검회의",
      "업무정리",
      "호텔 회의공간/공용공간",
      "도보",
      "3시간",
    ),
    e(
      "d4-05",
      4,
      "16:20",
      "19:30",
      "Delfshaven·Erasmusbrug·Bazar 저녁",
      "관광·식사",
      "Rotterdam",
      "트램+도보",
      "3시간 10분",
      {
        booking_url: "https://hotelbazar.nl/en/restaurant-bazar/",
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=Historic+Delfshaven&destination=Restaurant+Bazar+Rotterdam&waypoints=Erasmusbrug",
      },
    ),
    e(
      "d5-01",
      5,
      "08:00",
      "09:30",
      "조식·휴식",
      "개인정비",
      "Holiday Inn Express Rotterdam Central",
      "도보",
      "90분",
    ),
    e(
      "d5-02",
      5,
      "10:00",
      "12:00",
      "향후 일정 점검회의",
      "업무정리",
      "호텔 공용공간",
      "도보",
      "2시간",
    ),
    e(
      "d5-03",
      5,
      "12:20",
      "17:20",
      "Waterbus·킨더다이크 풍차군",
      "관광",
      "Rotterdam Erasmusbrug → Kinderdijk",
      "Waterbus+도보",
      "5시간",
      {
        booking_url: "https://www.waterbus.nl/en/",
        official_url: "https://kinderdijk.com/",
        notes: "무료 외부 산책 기준. 박물관 풍차 입장은 선택.",
      },
    ),
    e(
      "d5-04",
      5,
      "18:00",
      "19:30",
      "Fenix Food Factory·항만 저녁",
      "식사",
      "Katendrecht, Rotterdam",
      "메트로+도보",
      "90분",
      {
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Fenix+Food+Factory+Rotterdam",
      },
    ),
    e(
      "d6-01",
      6,
      "08:00",
      "08:50",
      "조식·체크아웃·짐 보관",
      "숙박",
      "Holiday Inn Express Rotterdam Central",
      "도보",
      "50분",
    ),
    e(
      "d6-02",
      6,
      "08:50",
      "09:20",
      "호텔 → Port of Rotterdam Authority",
      "교통",
      "Wilhelminakade 909, Rotterdam",
      "택시",
      "30분",
      {
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=Holiday+Inn+Express+Rotterdam+Central&destination=Wilhelminakade+909+Rotterdam",
      },
    ),
    e(
      "d6-03",
      6,
      "09:20",
      "11:30",
      "Port of Rotterdam Authority 회의",
      "업무",
      "World Port Center, Wilhelminakade 909",
      "도보",
      "2시간 10분",
      {
        official_url: "https://www.portofrotterdam.com/en",
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Wilhelminakade+909+Rotterdam",
        notes: "해상풍력 O&M 항만 추진·운영계획.",
      },
    ),
    e(
      "d6-04",
      6,
      "11:30",
      "12:25",
      "점심·ROG 이동",
      "식사·교통",
      "Wilhelminaplein → Drutenstraat 7",
      "택시",
      "55분",
    ),
    e(
      "d6-05",
      6,
      "12:25",
      "14:10",
      "Rotterdam Offshore Group 현장견학",
      "업무",
      "Drutenstraat 7, 3087 CC Rotterdam",
      "도보",
      "1시간 45분",
      {
        official_url: "https://www.rotterdamoffshore.com/",
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Rotterdam+Offshore+Group+Drutenstraat+7",
        notes: "선박·풍력설비 수리·정비 작업 수행체계.",
      },
    ),
    e(
      "d6-06",
      6,
      "14:10",
      "15:00",
      "ROG → TNO Rijswijk",
      "교통",
      "Drutenstraat 7 → Kesslerpark 1",
      "택시",
      "50분",
      {
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=Drutenstraat+7+Rotterdam&destination=Kesslerpark+1+Rijswijk",
      },
    ),
    e(
      "d6-07",
      6,
      "15:00",
      "16:30",
      "TNO Rijswijk 회의",
      "업무",
      "Kesslerpark 1, 2288 GS Rijswijk",
      "도보",
      "90분",
      {
        official_url:
          "https://www.tno.nl/en/about-tno/contact/locations/rijswijk-kesslerpark/",
        map_url:
          "https://www.google.com/maps/search/?api=1&query=TNO+Kesslerpark+1+Rijswijk",
        notes: "해상풍력 O&M 로봇점검·자동화 기술.",
      },
    ),
    e(
      "d6-08",
      6,
      "16:30",
      "17:40",
      "TNO → 로테르담 중앙역·짐 회수",
      "교통",
      "Rijswijk → Rotterdam Centraal",
      "택시+도보",
      "70분",
    ),
    e(
      "d6-09",
      6,
      "18:00",
      "9/8 00:05",
      "로테르담 → 함부르크",
      "교통",
      "Rotterdam Centraal → Hamburg Hbf",
      "NS/DB 국제열차",
      "약 6시간 5분",
      {
        booking_url:
          "https://www.nsinternational.com/en/germany/train-hamburg",
        official_url: "https://int.bahn.de/en",
        original_currency: "EUR",
        original_min: 33,
        original_max: 80,
        min_cost_krw: 210_000,
        max_cost_krw: 500_000,
        cost_basis: "4인·조기예약",
        notes:
          "계획서의 AMS→HAM 항공을 대체. NS 표준 소요시간은 약 6시간 4분이며 실제 출발시각은 발권 시 확정. 공항 이동·보안검색을 빼면 문전시간 차이가 작고 현재 KLM 4인 운임보다 크게 저렴.",
      },
    ),
    e(
      "d6-10",
      6,
      "00:05",
      "00:30",
      "함부르크 중앙역 → 호텔",
      "교통·숙박",
      "Motel One Hamburg-Fleetinsel",
      "택시",
      "25분",
    ),
    e(
      "d7-01",
      7,
      "08:30",
      "10:00",
      "조식·네덜란드 방문내용 정리",
      "업무정리",
      "Motel One Hamburg-Fleetinsel",
      "도보",
      "90분",
    ),
    e(
      "d7-02",
      7,
      "10:00",
      "12:00",
      "Miniatur Wunderland 또는 Speicherstadt 산책",
      "관광",
      "Speicherstadt",
      "도보",
      "2시간",
      {
        booking_url: "https://www.miniatur-wunderland.com/",
        notes: "비용 절약 시 외부 산책·창고지구만 이용.",
      },
    ),
    e(
      "d7-03",
      7,
      "12:00",
      "13:00",
      "Oberhafen-Kantine 점심",
      "식사",
      "Stockmeyerstraße 39, Hamburg",
      "도보/버스",
      "60분",
      {
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Oberhafen-Kantine+Hamburg",
      },
    ),
    e(
      "d7-04",
      7,
      "13:00",
      "13:15",
      "Skyborn Renewables 이동",
      "교통",
      "Ericusspitze 2-4, Hamburg",
      "도보",
      "15분",
    ),
    e(
      "d7-05",
      7,
      "13:15",
      "15:15",
      "Skyborn Renewables 회의",
      "업무",
      "Ericusspitze 2-4, 20457 Hamburg",
      "도보",
      "2시간",
      {
        official_url: "https://www.skybornrenewables.com/contact",
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Skyborn+Renewables+Ericusspitze+2-4",
        notes: "독일 해상풍력 사업개발 사례·인허가·수익성 논의.",
      },
    ),
    e(
      "d7-06",
      7,
      "15:30",
      "17:30",
      "Skyborn 회의내용 정리",
      "업무정리",
      "HafenCity",
      "도보",
      "2시간",
    ),
    e(
      "d7-07",
      7,
      "17:30",
      "20:30",
      "Elbphilharmonie Plaza·Landungsbrücken·저녁",
      "관광·식사",
      "Hamburg HafenCity",
      "도보+U-Bahn",
      "3시간",
      {
        booking_url:
          "https://www.elbphilharmonie.de/en/plaza-tickets",
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=Skyborn+Renewables+Hamburg&destination=Landungsbrucken&waypoints=Elbphilharmonie",
        notes: "플라자 현장권은 무료이나 사전예약 수수료가 있을 수 있음.",
      },
    ),
    e(
      "d8-01",
      8,
      "07:30",
      "09:15",
      "조식·체크아웃·함부르크 중앙역 이동",
      "교통",
      "Motel One Fleetinsel → Hamburg Hbf",
      "U-Bahn/택시",
      "1시간 45분",
    ),
    e(
      "d8-02",
      8,
      "09:53",
      "14:20",
      "함부르크 → 에스비에르",
      "교통",
      "Hamburg Hbf → Kolding → Esbjerg",
      "DB/DSB 열차",
      "약 4시간 30분",
      {
        booking_url: "https://int.bahn.de/en",
        original_currency: "EUR",
        original_min: 35,
        original_max: 70,
        min_cost_krw: 220_000,
        max_cost_krw: 450_000,
        cost_basis: "4인·조기예약",
        notes:
          "계획서의 3시간 38분 Kolding 대기편 대신 빠른 연결편 우선. 실제 시각은 DB 예약화면에서 확정.",
      },
    ),
    e(
      "d8-03",
      8,
      "14:20",
      "15:10",
      "호텔 이동·체크인",
      "숙박",
      "CABINN Plus Esbjerg, Torvegade 27",
      "도보",
      "50분",
    ),
    e(
      "d8-04",
      8,
      "15:30",
      "18:30",
      "Men at Sea·Fisheries and Maritime Museum 외부",
      "관광",
      "Sædding Strand, Esbjerg",
      "버스+도보",
      "3시간",
      {
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Men+at+Sea+Esbjerg",
        notes: "Men at Sea 외부 관람 무료.",
      },
    ),
    e(
      "d8-05",
      8,
      "19:00",
      "20:30",
      "Esbjerg Street Food 저녁",
      "식사",
      "Kongensgade, Esbjerg",
      "도보",
      "90분",
      {
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Esbjerg+Street+Food",
      },
    ),
    e(
      "d9-01",
      9,
      "07:30",
      "09:10",
      "조식·체크아웃·짐 보관",
      "숙박",
      "CABINN Plus Esbjerg",
      "도보",
      "1시간 40분",
    ),
    e(
      "d9-02",
      9,
      "09:10",
      "09:30",
      "Blue Water Shipping 이동",
      "교통",
      "Trafikhavnskaj 9, Esbjerg",
      "택시",
      "20분",
      {
        map_url:
          "https://www.google.com/maps/dir/?api=1&origin=CABINN+Plus+Esbjerg&destination=Blue+Water+Shipping+Trafikhavnskaj+9",
      },
    ),
    e(
      "d9-03",
      9,
      "09:30",
      "11:30",
      "Blue Water Shipping 회의",
      "업무",
      "Trafikhavnskaj 9, 6700 Esbjerg",
      "도보",
      "2시간",
      {
        official_url:
          "https://www.bws.net/contact/denmark/esbjerg",
        map_url:
          "https://www.google.com/maps/search/?api=1&query=Blue+Water+Shipping+Trafikhavnskaj+9+Esbjerg",
        notes: "해상풍력 터빈 공급망·운송·보관·통관 논의.",
      },
    ),
    e(
      "d9-04",
      9,
      "11:30",
      "13:00",
      "호텔 복귀·점심",
      "식사·교통",
      "Esbjerg Centrum",
      "택시+도보",
      "90분",
    ),
    e(
      "d9-05",
      9,
      "13:00",
      "15:30",
      "독일·덴마크 방문내용 정리",
      "업무정리",
      "CABINN Plus 라운지/도심 업무공간",
      "도보",
      "2시간 30분",
    ),
    e(
      "d9-06",
      9,
      "16:00",
      "19:05",
      "에스비에르 → 코펜하겐",
      "교통",
      "Esbjerg St. → København H",
      "DSB InterCity",
      "약 3시간",
      {
        booking_url: "https://www.dsb.dk/en/",
        min_cost_krw: 320_000,
        max_cost_krw: 600_000,
        cost_basis: "4인·Orange/일반 운임",
        notes:
          "다음 날 CPH 출국을 위해 전날 이동. EBJ→ABZ 항공·영국 환승을 제거.",
      },
    ),
    e(
      "d9-07",
      9,
      "19:05",
      "20:00",
      "코펜하겐 중앙역 → CABINN Metro",
      "교통·숙박",
      "Arne Jacobsens Allé 2, Copenhagen",
      "기차+도보",
      "55분",
      {
        booking_url: "https://en.cabinn.com/hotel/cabinn-metro",
      },
    ),
    e(
      "d9-08",
      9,
      "20:00",
      "21:00",
      "Field's Food Court 저녁",
      "식사",
      "Ørestad, Copenhagen",
      "도보",
      "60분",
      {
        official_url: "https://fields.steenstrom.dk/",
      },
    ),
    e(
      "d10-01",
      10,
      "06:45",
      "08:00",
      "체크아웃·코펜하겐공항 이동",
      "출국·교통",
      "CABINN Metro → CPH",
      "기차",
      "75분",
    ),
    e(
      "d10-02",
      10,
      "10:25",
      "14:45",
      "CPH → IST",
      "항공",
      "Copenhagen → Istanbul",
      "Turkish Airlines",
      "3시간 20분",
      {
        booking_url: "https://www.google.com/travel/flights",
      },
    ),
    e(
      "d10-03",
      10,
      "14:45",
      "17:00",
      "이스탄불 환승",
      "환승",
      "Istanbul Airport",
      "공항 내 이동",
      "2시간 15분",
    ),
    e(
      "d10-04",
      10,
      "17:00",
      "9/12 08:35",
      "IST → ICN",
      "항공",
      "Istanbul → Incheon",
      "Turkish Airlines",
      "9시간 35분",
      {
        booking_url: "https://www.google.com/travel/flights",
        notes:
          "CPH→IST→ICN 한 장 발권. 계획서 EBJ→ABZ→AMS→ICN보다 약 12시간 빠르고 현재 4인 기준 크게 저렴.",
      },
    ),
    e(
      "d11-01",
      11,
      "08:35",
      "09:35",
      "인천 도착·입국",
      "귀국",
      "Incheon International Airport",
      "도보",
      "60분",
    ),
  ];
}

function buildFlights(mode) {
  const saving = mode === "cost_optimized";
  return [
    {
      id: "f1",
      day_id: 1,
      date: "2026-09-02",
      flight_no: "LJ737 직항",
      origin: "ICN",
      destination: "RMQ",
      depart_time: "07:55",
      arrive_time: "09:40",
      min_krw: null,
      max_krw: null,
      status: "직항·자동가격",
      alternative: "ICN→TPE 후 THSR는 현재 더 비쌈",
      url: "https://www.jinair.com/",
      notes: "계획서 원안 유지",
      sort_order: 10,
    },
    {
      id: "f2",
      day_id: 3,
      date: "2026-09-04",
      flight_no: saving ? "CZ3098 + CZ307" : "CI73 직항",
      origin: "TPE",
      destination: "AMS",
      depart_time: saving ? "14:50" : "23:10",
      arrive_time: saving ? "06:35+1" : "07:40+1",
      min_krw: null,
      max_krw: null,
      status: saving ? "CAN 1회 환승·최저비용" : "직항·시간 우선",
      alternative: saving
        ? "CI73 직항은 4인 약 190만원 추가"
        : "중국남방 CAN 환승은 4인 약 190만원 절감",
      url: saving
        ? "https://www.csair.com/"
        : "https://www.china-airlines.com/",
      notes: saving
        ? "24시간 무비자 환승·수하물 연결발권 확인"
        : "광저우 환승과 약 8시간의 추가 이동 제거",
      sort_order: 20,
    },
    {
      id: "f3",
      day_id: 10,
      date: "2026-09-11",
      flight_no: "TK1784 + TK90",
      origin: "CPH",
      destination: "ICN",
      depart_time: "10:25",
      arrive_time: "08:35+1",
      min_krw: null,
      max_krw: null,
      status: "IST 1회 환승·권고",
      alternative: "EBJ→ABZ→AMS→ICN 계획서 원안",
      url: "https://www.turkishairlines.com/",
      notes: "에스비에르에서 전날 DSB로 코펜하겐 이동",
      sort_order: 30,
    },
  ];
}

const hotels = [
  {
    id: "h1",
    day_id: 1,
    name: "Holiday Inn Express Taichung Park",
    city: "Taichung",
    check_in: "2026-09-02",
    check_out: "2026-09-04",
    nights: 2,
    rooms: 2,
    min_krw: 300_000,
    max_krw: 550_000,
    status: "비용추천",
    alternative: "CHECK Inn Taichung LaiLai",
    url: "https://www.ihg.com/holidayinnexpress/hotels/us/en/taichung/txgsr/hoteldetail",
    notes:
      "웹 공개 시작가 약 US$55/실·박. 계획서 LaiLai와 같은 도심권·조식 포함 여부 확인.",
    sort_order: 10,
  },
  {
    id: "h2",
    day_id: 4,
    name: "Holiday Inn Express Rotterdam Central Station",
    city: "Rotterdam",
    check_in: "2026-09-05",
    check_out: "2026-09-07",
    nights: 2,
    rooms: 2,
    min_krw: 550_000,
    max_krw: 900_000,
    status: "비용추천",
    alternative: "The Usual Rotterdam",
    url: "https://www.ihg.com/holidayinnexpress/hotels/us/en/rotterdam/rtmcs/hoteldetail",
    notes:
      "웹 공개 시작가 약 US$97/실·박·조식 포함. 중앙역 도보권이라 함부르크 열차와 짐 보관에 유리.",
    sort_order: 20,
  },
  {
    id: "h3",
    day_id: 6,
    name: "Motel One Hamburg-Fleetinsel",
    city: "Hamburg",
    check_in: "2026-09-07",
    check_out: "2026-09-09",
    nights: 2,
    rooms: 2,
    min_krw: 650_000,
    max_krw: 1_050_000,
    status: "비용·동선추천",
    alternative: "Premier Inn Hamburg City Zentrum",
    url: "https://www.motel-one.com/en/hotels/hamburg/hotel-hamburg-fleetinsel/",
    notes:
      "공식 공개 시작가 약 US$109/실·박. Skyborn·Speicherstadt 도보권.",
    sort_order: 30,
  },
  {
    id: "h4",
    day_id: 8,
    name: "CABINN Plus Esbjerg",
    city: "Esbjerg",
    check_in: "2026-09-09",
    check_out: "2026-09-10",
    nights: 1,
    rooms: 2,
    min_krw: 350_000,
    max_krw: 500_000,
    status: "최저가추천",
    alternative: "Hotel Ansgar",
    url: "https://en.cabinn.com/hotel/cabinn-esbjerg-plus",
    notes:
      "공식 시작가 DKK875/실·박. Hotel Britannia보다 저렴하고 Blue Water Shipping 택시 약 10분.",
    sort_order: 40,
  },
  {
    id: "h5",
    day_id: 9,
    name: "CABINN Metro",
    city: "Copenhagen",
    check_in: "2026-09-10",
    check_out: "2026-09-11",
    nights: 1,
    rooms: 2,
    min_krw: 250_000,
    max_krw: 450_000,
    status: "공항접근추천",
    alternative: "Wakeup Copenhagen Bernstorffsgade",
    url: "https://en.cabinn.com/hotel/cabinn-metro",
    notes:
      "최근 공개 평균 약 DKK879/실·박. Ørestad역·CPH 공항 접근성 우선.",
    sort_order: 50,
  },
];

const meetings = [
  {
    id: "m1",
    day_id: 1,
    organization: "TIPC · Port of Taichung",
    agenda: "대만 해상풍력 O&M 항만 운영·개발계획",
    recommended_duration: "1시간 50분",
    contact: "",
    status: "일정협의 필요",
    photo_allowed: false,
    ppe_required: false,
    interpreter_needed: true,
    url: "https://tc.twport.com.tw/en",
    notes: "No.2, Sec.10, Taiwan Blvd., Wuqi",
    sort_order: 10,
  },
  {
    id: "m2",
    day_id: 2,
    organization: "VESTAS O&M Base",
    agenda: "터빈 O&M 기술·정비체계·예비품·TIPC 공동 결과공유",
    recommended_duration: "5시간",
    contact: "",
    status: "일정협의 필요",
    photo_allowed: true,
    ppe_required: true,
    interpreter_needed: true,
    url: "https://www.google.com/maps/search/?api=1&query=24.0765986,120.3773545",
    notes: "No.45, Lugong Rd., Lukang",
    sort_order: 20,
  },
  {
    id: "m3",
    day_id: 6,
    organization: "Port of Rotterdam Authority",
    agenda: "해상풍력 O&M 항만 추진·운영계획",
    recommended_duration: "2시간 10분",
    contact: "",
    status: "일정협의 필요",
    photo_allowed: false,
    ppe_required: false,
    interpreter_needed: false,
    url: "https://www.portofrotterdam.com/en",
    notes: "World Port Center, Wilhelminakade 909",
    sort_order: 30,
  },
  {
    id: "m4",
    day_id: 6,
    organization: "Rotterdam Offshore Group",
    agenda: "선박·풍력설비 수리·정비 작업 수행체계",
    recommended_duration: "1시간 45분",
    contact: "",
    status: "일정협의 필요",
    photo_allowed: true,
    ppe_required: true,
    interpreter_needed: false,
    url: "https://www.rotterdamoffshore.com/",
    notes: "Drutenstraat 7, Port no. 2226",
    sort_order: 40,
  },
  {
    id: "m5",
    day_id: 6,
    organization: "TNO Rijswijk · Kesslerpark",
    agenda: "해상풍력 O&M 로봇점검·자동화 기술",
    recommended_duration: "90분",
    contact: "",
    status: "일정협의 필요",
    photo_allowed: false,
    ppe_required: false,
    interpreter_needed: false,
    url: "https://www.tno.nl/en/about-tno/contact/locations/rijswijk-kesslerpark/",
    notes: "Kesslerpark 1, 2288 GS Rijswijk",
    sort_order: 50,
  },
  {
    id: "m6",
    day_id: 7,
    organization: "Skyborn Renewables",
    agenda: "독일 해상풍력 사업개발·인허가·수익성 사례",
    recommended_duration: "2시간",
    contact: "",
    status: "일정협의 필요",
    photo_allowed: false,
    ppe_required: false,
    interpreter_needed: false,
    url: "https://www.skybornrenewables.com/contact",
    notes: "Ericusspitze 2-4, Hamburg",
    sort_order: 60,
  },
  {
    id: "m7",
    day_id: 9,
    organization: "Blue Water Shipping · Esbjerg",
    agenda: "해상풍력 터빈 공급망·운송·보관·통관",
    recommended_duration: "2시간",
    contact: "",
    status: "일정협의 필요",
    photo_allowed: false,
    ppe_required: false,
    interpreter_needed: false,
    url: "https://www.bws.net/contact/denmark/esbjerg",
    notes: "Trafikhavnskaj 9, 6700 Esbjerg",
    sort_order: 70,
  },
];

const transportOptions = [
  {
    id: "t1",
    region: "대만",
    recommendation: "택시/기사차량 + THSR",
    reason: "4인 분산 이동은 택시가 대중교통 4인 합계와 유사하고 업무지 접근이 빠름",
    min_krw: 600_000,
    max_krw: 950_000,
    notes: "타이중항·루강 차량, 타이중→타오위안 THSR 포함",
    sort_order: 10,
  },
  {
    id: "t2",
    region: "네덜란드",
    recommendation: "NS 열차 + 업무일 택시",
    reason: "도심 주차비·렌터카 반납시간 제거",
    min_krw: 450_000,
    max_krw: 750_000,
    notes: "AMS→Rotterdam, Port Authority→ROG→TNO 택시",
    sort_order: 20,
  },
  {
    id: "t3",
    region: "로테르담→함부르크",
    recommendation: "NS/DB 국제열차",
    reason: "항공보다 4인 약 100만원 이상 절약 가능·도심 간 이동",
    min_krw: 210_000,
    max_krw: 500_000,
    notes: "네덜란드발 조기운임 €33부터·로테르담 기준 약 6시간 4분",
    sort_order: 30,
  },
  {
    id: "t4",
    region: "함부르크→에스비에르",
    recommendation: "DB/DSB 열차",
    reason: "4인 렌터카 국경 편도반납료 회피",
    min_krw: 220_000,
    max_krw: 450_000,
    notes: "조기운임 US$35/€30대부터·빠른 Kolding 연결편 선택",
    sort_order: 40,
  },
  {
    id: "t5",
    region: "에스비에르→코펜하겐·현지교통",
    recommendation: "DSB InterCity + 대중교통",
    reason: "EBJ→ABZ 항공과 영국 환승 제거",
    min_krw: 620_000,
    max_krw: 900_000,
    notes: "Orange 운임 우선·코펜하겐 공항 전날 이동",
    sort_order: 50,
  },
];

const restaurants = [
  {
    id: "r1",
    day_id: 1,
    name: "Wuqi Fishing Harbor",
    city: "Taichung Port",
    meal_type: "간식·이른 저녁",
    price_per_person: "TWD 300~700",
    url: "https://www.google.com/maps/search/?api=1&query=Wuqi+Fishing+Harbor",
    notes: "TIPC에서 가까운 해산물시장",
    sort_order: 10,
  },
  {
    id: "r2",
    day_id: 2,
    name: "Chun Shui Tang Siwei Original Store",
    city: "Taichung",
    meal_type: "저녁",
    price_per_person: "TWD 350~700",
    url: "https://www.chunshuitang.com.tw/",
    notes: "버블티 원조점·예약 또는 대기시간 확인",
    sort_order: 20,
  },
  {
    id: "r3",
    day_id: 4,
    name: "Markthal Rotterdam",
    city: "Rotterdam",
    meal_type: "점심",
    price_per_person: "EUR 12~25",
    url: "https://www.markthal.nl/en/",
    notes: "선택지가 많고 관광 동선과 결합",
    sort_order: 30,
  },
  {
    id: "r4",
    day_id: 4,
    name: "Restaurant Bazar",
    city: "Rotterdam",
    meal_type: "저녁",
    price_per_person: "EUR 20~35",
    url: "https://hotelbazar.nl/en/restaurant-bazar/",
    notes: "중동·북아프리카 요리·도심 중가",
    sort_order: 40,
  },
  {
    id: "r5",
    day_id: 7,
    name: "Oberhafen-Kantine",
    city: "Hamburg",
    meal_type: "점심",
    price_per_person: "EUR 18~30",
    url: "https://www.google.com/maps/search/?api=1&query=Oberhafen-Kantine+Hamburg",
    notes: "Skyborn·Speicherstadt 동선",
    sort_order: 50,
  },
  {
    id: "r6",
    day_id: 8,
    name: "Esbjerg Street Food",
    city: "Esbjerg",
    meal_type: "저녁",
    price_per_person: "DKK 100~180",
    url: "https://www.google.com/maps/search/?api=1&query=Esbjerg+Street+Food",
    notes: "Hotel Britannia 레스토랑보다 저렴한 선택",
    sort_order: 60,
  },
  {
    id: "r7",
    day_id: 9,
    name: "Field's Food Court",
    city: "Copenhagen",
    meal_type: "저녁",
    price_per_person: "DKK 100~180",
    url: "https://fields.steenstrom.dk/",
    notes: "CABINN Metro 도보권",
    sort_order: 70,
  },
];

function buildMapPoints(mode) {
  const saving = mode === "cost_optimized";
  const day3 = saving
    ? [
        {
          id: "p14",
          day_id: 3,
          name: "Holiday Inn Express Taichung Park",
          lat: 24.1406,
          lng: 120.6841,
          sort_order: 1,
          segment_type: "car",
          popup: "09:00 출발",
          url: "",
        },
        {
          id: "p15",
          day_id: 3,
          name: "THSR Taichung",
          lat: 24.1127,
          lng: 120.616,
          sort_order: 2,
          segment_type: "car",
          popup: "고속철도 환승",
          url: "https://en.thsrc.com.tw/",
        },
        {
          id: "p16",
          day_id: 3,
          name: "THSR Taoyuan",
          lat: 25.0138,
          lng: 121.2147,
          sort_order: 3,
          segment_type: "hsr",
          popup: "Airport MRT 환승",
          url: "",
        },
        {
          id: "p17",
          day_id: 3,
          name: "Taoyuan Airport",
          lat: 25.0797,
          lng: 121.2342,
          sort_order: 4,
          segment_type: "subway",
          popup: "14:50 출발",
          url: "",
        },
        {
          id: "p18",
          day_id: 3,
          name: "Guangzhou Airport",
          lat: 23.3924,
          lng: 113.2988,
          sort_order: 5,
          segment_type: "flight",
          popup: "7시간 5분 환승",
          url: "",
        },
        {
          id: "p19",
          day_id: 3,
          name: "Schiphol Airport",
          lat: 52.3105,
          lng: 4.7683,
          sort_order: 6,
          segment_type: "flight",
          popup: "9/5 06:35 도착",
          url: "",
        },
      ]
    : [
        {
          id: "p14",
          day_id: 3,
          name: "Holiday Inn Express Taichung Park",
          lat: 24.1406,
          lng: 120.6841,
          sort_order: 1,
          segment_type: "car",
          popup: "출발",
          url: "",
        },
        {
          id: "p15",
          day_id: 3,
          name: "National Taichung Theater",
          lat: 24.1629,
          lng: 120.6404,
          sort_order: 2,
          segment_type: "car",
          popup: "관광",
          url: "https://www.npac-ntt.org/en",
        },
        {
          id: "p16",
          day_id: 3,
          name: "THSR Taichung",
          lat: 24.1127,
          lng: 120.616,
          sort_order: 3,
          segment_type: "car",
          popup: "고속철도 환승",
          url: "https://en.thsrc.com.tw/",
        },
        {
          id: "p17",
          day_id: 3,
          name: "THSR Taoyuan",
          lat: 25.0138,
          lng: 121.2147,
          sort_order: 4,
          segment_type: "hsr",
          popup: "Airport MRT 환승",
          url: "",
        },
        {
          id: "p18",
          day_id: 3,
          name: "Taoyuan Airport",
          lat: 25.0797,
          lng: 121.2342,
          sort_order: 5,
          segment_type: "subway",
          popup: "23:10 출발",
          url: "",
        },
        {
          id: "p19",
          day_id: 3,
          name: "Schiphol Airport",
          lat: 52.3105,
          lng: 4.7683,
          sort_order: 6,
          segment_type: "flight",
          popup: "9/5 07:40 도착",
          url: "",
        },
      ];

  return [
    {
      id: "p01",
      day_id: 1,
      name: "인천공항",
      lat: 37.4587,
      lng: 126.442,
      sort_order: 1,
      segment_type: "flight",
      popup: "07:55 출발",
      url: "",
    },
    {
      id: "p02",
      day_id: 1,
      name: "Taichung Airport",
      lat: 24.2647,
      lng: 120.6208,
      sort_order: 2,
      segment_type: "flight",
      popup: "09:40 도착",
      url: "",
    },
    {
      id: "p03",
      day_id: 1,
      name: "Holiday Inn Express Taichung Park",
      lat: 24.1406,
      lng: 120.6841,
      sort_order: 3,
      segment_type: "car",
      popup: "짐 보관",
      url: "https://www.ihg.com/holidayinnexpress/hotels/us/en/taichung/txgsr/hoteldetail",
    },
    {
      id: "p04",
      day_id: 1,
      name: "TIPC · Port of Taichung",
      lat: 24.256,
      lng: 120.521,
      sort_order: 4,
      segment_type: "car",
      popup: "14:10 회의",
      url: "https://tc.twport.com.tw/en",
    },
    {
      id: "p05",
      day_id: 1,
      name: "Wuqi Fishing Harbor",
      lat: 24.2926,
      lng: 120.5212,
      sort_order: 5,
      segment_type: "car",
      popup: "해산물시장",
      url: "",
    },
    {
      id: "p06",
      day_id: 1,
      name: "Gaomei Wetlands",
      lat: 24.3124,
      lng: 120.5496,
      sort_order: 6,
      segment_type: "car",
      popup: "일몰",
      url: "",
    },
    {
      id: "p07",
      day_id: 1,
      name: "Holiday Inn Express Taichung Park",
      lat: 24.1406,
      lng: 120.6841,
      sort_order: 7,
      segment_type: "car",
      popup: "숙박",
      url: "",
    },
    {
      id: "p08",
      day_id: 2,
      name: "Holiday Inn Express Taichung Park",
      lat: 24.1406,
      lng: 120.6841,
      sort_order: 1,
      segment_type: "car",
      popup: "08:40 출발",
      url: "",
    },
    {
      id: "p09",
      day_id: 2,
      name: "VESTAS O&M Base",
      lat: 24.0766,
      lng: 120.3774,
      sort_order: 2,
      segment_type: "car",
      popup: "10:30 회의",
      url: "",
    },
    {
      id: "p10",
      day_id: 2,
      name: "Lukang Old Street",
      lat: 24.056,
      lng: 120.435,
      sort_order: 3,
      segment_type: "car",
      popup: "관광",
      url: "",
    },
    {
      id: "p11",
      day_id: 2,
      name: "Holiday Inn Express Taichung Park",
      lat: 24.1406,
      lng: 120.6841,
      sort_order: 4,
      segment_type: "car",
      popup: "숙박",
      url: "",
    },
    ...day3,
    {
      id: "p20",
      day_id: 4,
      name: "Schiphol Airport",
      lat: 52.3105,
      lng: 4.7683,
      sort_order: 1,
      segment_type: "rail",
      popup: saving ? "06:35 도착" : "07:40 도착",
      url: "",
    },
    {
      id: "p21",
      day_id: 4,
      name: "Rotterdam Centraal",
      lat: 51.9244,
      lng: 4.4699,
      sort_order: 2,
      segment_type: "rail",
      popup: "NS Intercity",
      url: "",
    },
    {
      id: "p22",
      day_id: 4,
      name: "Holiday Inn Express Rotterdam Central",
      lat: 51.9255,
      lng: 4.478,
      sort_order: 3,
      segment_type: "subway",
      popup: "짐 보관·숙박",
      url: "https://www.ihg.com/holidayinnexpress/hotels/us/en/rotterdam/rtmcs/hoteldetail",
    },
    {
      id: "p23",
      day_id: 4,
      name: "Markthal Rotterdam",
      lat: 51.9201,
      lng: 4.4869,
      sort_order: 4,
      segment_type: "subway",
      popup: "관광·점심",
      url: "https://www.markthal.nl/en/",
    },
    {
      id: "p24",
      day_id: 4,
      name: "Historic Delfshaven",
      lat: 51.9087,
      lng: 4.4481,
      sort_order: 5,
      segment_type: "subway",
      popup: "관광",
      url: "",
    },
    {
      id: "p25",
      day_id: 4,
      name: "Restaurant Bazar",
      lat: 51.916,
      lng: 4.477,
      sort_order: 6,
      segment_type: "subway",
      popup: "저녁",
      url: "https://hotelbazar.nl/en/restaurant-bazar/",
    },
    {
      id: "p26",
      day_id: 5,
      name: "Holiday Inn Express Rotterdam Central",
      lat: 51.9255,
      lng: 4.478,
      sort_order: 1,
      segment_type: "subway",
      popup: "출발",
      url: "",
    },
    {
      id: "p27",
      day_id: 5,
      name: "Erasmusbrug Waterbus",
      lat: 51.909,
      lng: 4.486,
      sort_order: 2,
      segment_type: "subway",
      popup: "Waterbus",
      url: "https://www.waterbus.nl/en/",
    },
    {
      id: "p28",
      day_id: 5,
      name: "Kinderdijk",
      lat: 51.882,
      lng: 4.6331,
      sort_order: 3,
      segment_type: "subway",
      popup: "풍차군",
      url: "https://kinderdijk.com/",
    },
    {
      id: "p29",
      day_id: 5,
      name: "Fenix Food Factory",
      lat: 51.9045,
      lng: 4.485,
      sort_order: 4,
      segment_type: "subway",
      popup: "저녁",
      url: "",
    },
    {
      id: "p30",
      day_id: 6,
      name: "Holiday Inn Express Rotterdam Central",
      lat: 51.9255,
      lng: 4.478,
      sort_order: 1,
      segment_type: "car",
      popup: "08:50 출발",
      url: "",
    },
    {
      id: "p31",
      day_id: 6,
      name: "Port of Rotterdam Authority",
      lat: 51.9044,
      lng: 4.4841,
      sort_order: 2,
      segment_type: "car",
      popup: "09:20 회의",
      url: "https://www.portofrotterdam.com/en",
    },
    {
      id: "p32",
      day_id: 6,
      name: "Rotterdam Offshore Group",
      lat: 51.8788,
      lng: 4.445,
      sort_order: 3,
      segment_type: "car",
      popup: "12:25 현장견학",
      url: "https://www.rotterdamoffshore.com/",
    },
    {
      id: "p33",
      day_id: 6,
      name: "TNO Kesslerpark",
      lat: 52.036,
      lng: 4.325,
      sort_order: 4,
      segment_type: "car",
      popup: "15:00 회의",
      url: "https://www.tno.nl/en/about-tno/contact/locations/rijswijk-kesslerpark/",
    },
    {
      id: "p34",
      day_id: 6,
      name: "Rotterdam Centraal",
      lat: 51.9244,
      lng: 4.4699,
      sort_order: 5,
      segment_type: "car",
      popup: "국제열차",
      url: "",
    },
    {
      id: "p35",
      day_id: 6,
      name: "Hamburg Hbf",
      lat: 53.5527,
      lng: 10.0067,
      sort_order: 6,
      segment_type: "rail",
      popup: "약 00:05 도착",
      url: "",
    },
    {
      id: "p36",
      day_id: 6,
      name: "Motel One Hamburg-Fleetinsel",
      lat: 53.5484,
      lng: 9.9848,
      sort_order: 7,
      segment_type: "subway",
      popup: "숙박",
      url: "https://www.motel-one.com/en/hotels/hamburg/hotel-hamburg-fleetinsel/",
    },
    {
      id: "p37",
      day_id: 7,
      name: "Motel One Hamburg-Fleetinsel",
      lat: 53.5484,
      lng: 9.9848,
      sort_order: 1,
      segment_type: "subway",
      popup: "출발",
      url: "",
    },
    {
      id: "p38",
      day_id: 7,
      name: "Speicherstadt",
      lat: 53.5439,
      lng: 9.989,
      sort_order: 2,
      segment_type: "subway",
      popup: "관광",
      url: "",
    },
    {
      id: "p39",
      day_id: 7,
      name: "Skyborn Renewables",
      lat: 53.5454,
      lng: 10.0032,
      sort_order: 3,
      segment_type: "subway",
      popup: "13:15 회의",
      url: "https://www.skybornrenewables.com/contact",
    },
    {
      id: "p40",
      day_id: 7,
      name: "Elbphilharmonie",
      lat: 53.5413,
      lng: 9.9841,
      sort_order: 4,
      segment_type: "subway",
      popup: "관광",
      url: "https://www.elbphilharmonie.de/en/plaza-tickets",
    },
    {
      id: "p41",
      day_id: 8,
      name: "Motel One Hamburg-Fleetinsel",
      lat: 53.5484,
      lng: 9.9848,
      sort_order: 1,
      segment_type: "subway",
      popup: "출발",
      url: "",
    },
    {
      id: "p42",
      day_id: 8,
      name: "Hamburg Hbf",
      lat: 53.5527,
      lng: 10.0067,
      sort_order: 2,
      segment_type: "subway",
      popup: "09:53 출발 예정",
      url: "",
    },
    {
      id: "p43",
      day_id: 8,
      name: "Esbjerg Station",
      lat: 55.4667,
      lng: 8.4578,
      sort_order: 3,
      segment_type: "rail",
      popup: "14:20 도착 예정",
      url: "",
    },
    {
      id: "p44",
      day_id: 8,
      name: "CABINN Plus Esbjerg",
      lat: 55.4676,
      lng: 8.4525,
      sort_order: 4,
      segment_type: "subway",
      popup: "숙박",
      url: "https://en.cabinn.com/hotel/cabinn-esbjerg-plus",
    },
    {
      id: "p45",
      day_id: 8,
      name: "Men at Sea",
      lat: 55.487,
      lng: 8.4108,
      sort_order: 5,
      segment_type: "subway",
      popup: "관광",
      url: "",
    },
    {
      id: "p46",
      day_id: 9,
      name: "CABINN Plus Esbjerg",
      lat: 55.4676,
      lng: 8.4525,
      sort_order: 1,
      segment_type: "car",
      popup: "09:10 출발",
      url: "",
    },
    {
      id: "p47",
      day_id: 9,
      name: "Blue Water Shipping",
      lat: 55.465,
      lng: 8.443,
      sort_order: 2,
      segment_type: "car",
      popup: "09:30 회의",
      url: "https://www.bws.net/contact/denmark/esbjerg",
    },
    {
      id: "p48",
      day_id: 9,
      name: "Esbjerg Station",
      lat: 55.4667,
      lng: 8.4578,
      sort_order: 3,
      segment_type: "car",
      popup: "16:00 출발 예정",
      url: "",
    },
    {
      id: "p49",
      day_id: 9,
      name: "Copenhagen Central",
      lat: 55.6727,
      lng: 12.5646,
      sort_order: 4,
      segment_type: "rail",
      popup: "19:05 도착 예정",
      url: "",
    },
    {
      id: "p50",
      day_id: 9,
      name: "CABINN Metro",
      lat: 55.6307,
      lng: 12.5778,
      sort_order: 5,
      segment_type: "subway",
      popup: "숙박",
      url: "https://en.cabinn.com/hotel/cabinn-metro",
    },
    {
      id: "p51",
      day_id: 10,
      name: "CABINN Metro",
      lat: 55.6307,
      lng: 12.5778,
      sort_order: 1,
      segment_type: "subway",
      popup: "06:45 출발",
      url: "",
    },
    {
      id: "p52",
      day_id: 10,
      name: "Copenhagen Airport",
      lat: 55.6181,
      lng: 12.656,
      sort_order: 2,
      segment_type: "subway",
      popup: "10:25 출발",
      url: "",
    },
    {
      id: "p53",
      day_id: 10,
      name: "Istanbul Airport",
      lat: 41.2753,
      lng: 28.7519,
      sort_order: 3,
      segment_type: "flight",
      popup: "2시간 15분 환승",
      url: "",
    },
    {
      id: "p54",
      day_id: 10,
      name: "인천공항",
      lat: 37.4587,
      lng: 126.442,
      sort_order: 4,
      segment_type: "flight",
      popup: "9/12 08:35 도착",
      url: "",
    },
    {
      id: "p55",
      day_id: 11,
      name: "인천공항",
      lat: 37.4587,
      lng: 126.442,
      sort_order: 1,
      segment_type: "flight",
      popup: "08:35 도착·입국",
      url: "",
    },
  ];
}

function buildBudget(mode) {
  return [
    {
      id: "b1",
      category: "항공",
      label: "3개 장거리·국제 항공 구간·4인 자동조회",
      min_krw: 0,
      max_krw: 0,
      notes: "선택 일정의 Google Flights 채택가 합계로 자동 대체",
      sort_order: 10,
    },
    {
      id: "b2",
      category: "숙박",
      label: "호텔 8박·2실",
      min_krw: 2_100_000,
      max_krw: 3_450_000,
      notes:
        "Taichung 2, Rotterdam 2, Hamburg 2, Esbjerg 1, Copenhagen 1",
      sort_order: 20,
    },
    {
      id: "b3",
      category: "교통",
      label: "택시·기사차량·THSR·유럽철도·대중교통",
      min_krw: 2_100_000,
      max_krw: 3_400_000,
      notes: "4인 기준·국경 편도 렌터카 미사용",
      sort_order: 30,
    },
    {
      id: "b4",
      category: "식비·관광",
      label: "식사·입장권·Waterbus",
      min_krw: 3_000_000,
      max_krw: 4_800_000,
      notes: "무료 외부 관광 중심·유료 박물관은 선택",
      sort_order: 40,
    },
    {
      id: "b5",
      category: "기타",
      label: "보험·PPE·통역·수하물·좌석료",
      min_krw: 1_000_000,
      max_krw: 1_800_000,
      notes:
        mode === "cost_optimized"
          ? "중국남방 연결발권 수하물·좌석료 확인"
          : "직항 수하물·좌석료 확인",
      sort_order: 50,
    },
  ];
}

function buildSeed(mode) {
  return {
    days: buildDays(mode),
    events: buildEvents(mode),
    flights: buildFlights(mode),
    hotels,
    meetings,
    transport_options: transportOptions,
    restaurants,
    map_points: buildMapPoints(mode),
    budget_items: buildBudget(mode),
  };
}

export const ITINERARIES = {
  cost_optimized: {
    meta: planMeta.cost_optimized,
    officialSeed: buildSeed("cost_optimized"),
  },
  time_optimized: {
    meta: planMeta.time_optimized,
    officialSeed: buildSeed("time_optimized"),
  },
};
